// renderers/react/src/v0_9/components/Card.tsx
import React, { memo } from 'react';
import type { A2UIComponentProps } from '../core/types.js';
import { ComponentHost } from '../core/ComponentHost.js';
import { useA2UI } from '../core/A2UIProvider.js';

/**
 * Card component — wraps a single child in a card container.
 */
export const Card = memo(function Card({
  props,
  surfaceId,
  dataContextPath,
  registry,
}: A2UIComponentProps) {
  const { surfaceGroup } = useA2UI();
  const surface = surfaceGroup.getSurface(surfaceId);
  const childId = props.child?.raw;

  if (!surface || !childId) return null;

  return (
    <div className="a2ui-card">
      <ComponentHost
        surface={surface}
        componentId={childId}
        dataContextPath={dataContextPath}
        registry={registry}
      />
    </div>
  );
});

// renderers/svelte/src/components/Card.svelte
<script lang="ts">
  import type { SurfaceModel, ComponentApi } from '@a2ui/web_core/v0_9';
  import type { ComponentRegistry, BoundProperty } from '../core/types.js';
  import ComponentHost from '../core/ComponentHost.svelte';

  interface Props {
    props: Record<string, BoundProperty>;
    surface: SurfaceModel<ComponentApi>;
    componentId: string;
    dataContextPath: string;
    registry: ComponentRegistry;
  }

  let { props, surface, dataContextPath, registry }: Props = $props();

  const child = $derived(props.child?.value);
</script>

<div class="a2ui-card">
  {#if child}
    <ComponentHost
      {surface}
      componentId={child}
      {dataContextPath}
      {registry}
    />
  {/if}
</div>
