// renderers/react/src/v0_9/components/DateTimeInput.tsx
import React, { memo, useCallback } from 'react';
import type { A2UIComponentProps } from '../core/types.js';

/**
 * DateTimeInput component — date and/or time input with value binding.
 */
export const DateTimeInput = memo(function DateTimeInput({
  props,
}: A2UIComponentProps) {
  const label = props.label?.value ?? '';
  const value = props.value?.value ?? '';
  const enableDate = props.enableDate?.value ?? false;
  const enableTime = props.enableTime?.value ?? false;
  const min = props.min?.value;
  const max = props.max?.value;

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      props.value?.onUpdate(e.target.value);
    },
    [props.value],
  );

  let inputType = 'text';
  if (enableDate && enableTime) {
    inputType = 'datetime-local';
  } else if (enableDate) {
    inputType = 'date';
  } else if (enableTime) {
    inputType = 'time';
  }

  return (
    <div className="a2ui-datetime-input">
      {label && <label className="a2ui-datetime-input__label">{label}</label>}
      <input
        className="a2ui-datetime-input__input"
        type={inputType}
        value={value}
        min={min}
        max={max}
        onChange={handleChange}
      />
    </div>
  );
});

// renderers/svelte/src/components/DateTimeInput.svelte
<script lang="ts">
  import type { SurfaceModel, ComponentApi } from '@a2ui/web_core/v0_9';
  import type { ComponentRegistry, BoundProperty } from '../core/types.js';

  interface Props {
    props: Record<string, BoundProperty>;
    surface: SurfaceModel<ComponentApi>;
    componentId: string;
    dataContextPath: string;
    registry: ComponentRegistry;
  }

  let { props, componentId }: Props = $props();

  const fieldId = $derived(`a2ui-dt-${componentId}`);
  const label = $derived(props.label?.value ?? '');
  const value = $derived(props.value?.value ?? '');
  const enableDate = $derived(props.enableDate?.value ?? false);
  const enableTime = $derived(props.enableTime?.value ?? false);
  const min = $derived(props.min?.value ?? '');
  const max = $derived(props.max?.value ?? '');

  const inputType = $derived.by(() => {
    if (enableDate && enableTime) return 'datetime-local';
    if (enableTime) return 'time';
    return 'date';
  });

  function handleInput(event: Event) {
    const target = event.target as HTMLInputElement;
    props.value?.onUpdate(target.value);
  }
</script>

<div class="a2ui-datetime-input">
  {#if label}
    <label class="a2ui-datetime-label" for={fieldId}>{label}</label>
  {/if}
  <input
    id={fieldId}
    class="a2ui-datetime-input-field"
    type={inputType}
    value={value}
    min={min || undefined}
    max={max || undefined}
    oninput={handleInput}
  />
</div>
