// renderers/react/src/v0_9/components/Image.tsx
import React, { memo } from 'react';
import type { A2UIComponentProps } from '../core/types.js';

/**
 * Image component — renders an img element with url, fit, and variant.
 */
export const Image = memo(function Image({
  props,
}: A2UIComponentProps) {
  const url = props.url?.value ?? '';
  const fit = props.fit?.value ?? 'fill';
  const variant = props.variant?.value ?? 'mediumFeature';

  const fitMap: Record<string, string> = {
    contain: 'contain',
    cover: 'cover',
    fill: 'fill',
    none: 'none',
    scaleDown: 'scale-down',
  };

  return (
    <img
      className={`a2ui-image a2ui-image--${variant}`}
      src={url}
      alt=""
      style={{ objectFit: (fitMap[fit] ?? 'fill') as React.CSSProperties['objectFit'] }}
    />
  );
});

// renderers/svelte/src/components/Image.svelte
<script lang="ts">
  import type { SurfaceModel, ComponentApi } from '@a2ui/web_core/v0_9';
  import type { ComponentRegistry, BoundProperty } from '../core/types.js';

  interface Props {
    props: Record<string, BoundProperty>;
    surface: SurfaceModel<ComponentApi>;
    componentId: string;
    dataContextPath: string;
    registry: ComponentRegistry;
  }

  let { props }: Props = $props();

  const url = $derived(props.url?.value ?? '');
  const fit = $derived(props.fit?.value ?? 'fill');
  const variant = $derived(props.variant?.value ?? 'mediumFeature');

  const objectFit = $derived(
    fit === 'scaleDown' ? 'scale-down' : fit
  );
</script>

<img
  class="a2ui-image {variant}"
  src={url}
  alt=""
  style:object-fit={objectFit}
/>
