// renderers/react/src/v0_9/components/List.tsx
import React, { memo } from 'react';
import type { A2UIComponentProps } from '../core/types.js';
import { ComponentHost } from '../core/ComponentHost.js';
import { getNormalizedPath } from '../core/useComponent.js';
import { useA2UI } from '../core/A2UIProvider.js';

/**
 * List component — arranges children with a configurable direction.
 */
export const List = memo(function List({
  props,
  surfaceId,
  dataContextPath,
  registry,
}: A2UIComponentProps) {
  const { surfaceGroup } = useA2UI();
  const surface = surfaceGroup.getSurface(surfaceId);

  const direction = props.direction?.value ?? 'vertical';
  const align = props.align?.value ?? 'stretch';
  const childrenRaw = props.children?.raw;
  const childrenValue = props.children?.value;

  if (!surface) return null;

  const alignMap: Record<string, string> = {
    start: 'flex-start',
    center: 'center',
    end: 'flex-end',
    stretch: 'stretch',
  };

  const style: React.CSSProperties = {
    display: 'flex',
    flexDirection: direction === 'horizontal' ? 'row' : 'column',
    alignItems: alignMap[align] ?? 'stretch',
  };

  // Repeating template: { componentId, path }
  if (childrenRaw && typeof childrenRaw === 'object' && 'componentId' in childrenRaw) {
    const items = Array.isArray(childrenValue) ? childrenValue : [];
    return (
      <div className="a2ui-list" style={style}>
        {items.map((_: any, index: number) => (
          <ComponentHost
            key={index}
            surface={surface}
            componentId={childrenRaw.componentId}
            dataContextPath={getNormalizedPath(childrenRaw.path, dataContextPath, index)}
            registry={registry}
          />
        ))}
      </div>
    );
  }

  // Static array of component IDs
  const childIds = Array.isArray(childrenRaw) ? childrenRaw : [];
  return (
    <div className="a2ui-list" style={style}>
      {childIds.map((childId: string) => (
        <ComponentHost
          key={childId}
          surface={surface}
          componentId={childId}
          dataContextPath={dataContextPath}
          registry={registry}
        />
      ))}
    </div>
  );
});

// renderers/svelte/src/components/List.svelte
<script lang="ts">
  import type { SurfaceModel, ComponentApi } from '@a2ui/web_core/v0_9';
  import type { ComponentRegistry, BoundProperty } from '../core/types.js';
  import ComponentHost from '../core/ComponentHost.svelte';

  interface Props {
    props: Record<string, BoundProperty>;
    surface: SurfaceModel<ComponentApi>;
    componentId: string;
    dataContextPath: string;
    registry: ComponentRegistry;
  }

  let { props, surface, dataContextPath, registry }: Props = $props();

  const direction = $derived(props.direction?.value ?? 'vertical');
  const align = $derived(props.align?.value ?? 'stretch');

  const children = $derived.by(() => {
    const raw = props.children?.value;
    return Array.isArray(raw) ? raw : [];
  });

  const isRepeating = $derived(!!props.children?.raw?.componentId);
  const templateId = $derived(props.children?.raw?.componentId);

  const flexDirection = $derived(direction === 'horizontal' ? 'row' : 'column');

  function getNormalizedPath(path: string, dcp: string, index: number): string {
    let normalized = path || '';
    if (!normalized.startsWith('/')) {
      const base = dcp === '/' ? '' : dcp;
      normalized = `${base}/${normalized}`;
    }
    if (normalized.endsWith('/')) normalized = normalized.slice(0, -1);
    return `${normalized}/${index}`;
  }
</script>

<div
  class="a2ui-list {direction}"
  style:display="flex"
  style:flex-direction={flexDirection}
  style:gap="8px"
  style:align-items={align}
>
  {#if !isRepeating}
    {#each children as childId (childId)}
      <div class="a2ui-list-item">
        <ComponentHost
          {surface}
          componentId={childId}
          {dataContextPath}
          {registry}
        />
      </div>
    {/each}
  {:else}
    {#each children as _, i (i)}
      <div class="a2ui-list-item">
        <ComponentHost
          {surface}
          componentId={templateId}
          dataContextPath={getNormalizedPath(props.children?.raw?.path, dataContextPath, i)}
          {registry}
        />
      </div>
    {/each}
  {/if}
</div>
