// renderers/react/src/v0_9/components/Modal.tsx
import React, { memo, useState, useCallback, useRef, useEffect } from 'react';
import type { A2UIComponentProps } from '../core/types.js';
import { ComponentHost } from '../core/ComponentHost.js';
import { useA2UI } from '../core/A2UIProvider.js';

/**
 * Modal component — trigger element that opens a dialog with content.
 */
export const Modal = memo(function Modal({
  props,
  surfaceId,
  dataContextPath,
  registry,
}: A2UIComponentProps) {
  const { surfaceGroup } = useA2UI();
  const surface = surfaceGroup.getSurface(surfaceId);
  const [isOpen, setIsOpen] = useState(false);
  const dialogRef = useRef<HTMLDialogElement>(null);

  const triggerId = props.trigger?.raw;
  const contentId = props.content?.raw;

  const openModal = useCallback(() => setIsOpen(true), []);
  const closeModal = useCallback(() => setIsOpen(false), []);

  useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;

    if (isOpen && !dialog.open) {
      dialog.showModal();
    }

    const handleClose = () => setIsOpen(false);
    dialog.addEventListener('close', handleClose);
    return () => dialog.removeEventListener('close', handleClose);
  }, [isOpen]);

  const handleBackdropClick = useCallback(
    (e: React.MouseEvent<HTMLDialogElement>) => {
      if (e.target === e.currentTarget) closeModal();
    },
    [closeModal],
  );

  if (!surface) return null;

  if (!isOpen) {
    return (
      <div className="a2ui-modal">
        <div className="a2ui-modal__trigger" onClick={openModal} style={{ cursor: 'pointer' }}>
          {triggerId && (
            <ComponentHost
              surface={surface}
              componentId={triggerId}
              dataContextPath={dataContextPath}
              registry={registry}
            />
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="a2ui-modal">
      <dialog
        ref={dialogRef}
        className="a2ui-modal__dialog"
        onClick={handleBackdropClick}
      >
        <div className="a2ui-modal__content">
          <button
            className="a2ui-modal__close"
            onClick={closeModal}
            aria-label="Close modal"
          >
            close
          </button>
          {contentId && (
            <ComponentHost
              surface={surface}
              componentId={contentId}
              dataContextPath={dataContextPath}
              registry={registry}
            />
          )}
        </div>
      </dialog>
    </div>
  );
});

// renderers/svelte/src/components/Modal.svelte
<script lang="ts">
  import type { SurfaceModel, ComponentApi } from '@a2ui/web_core/v0_9';
  import type { ComponentRegistry, BoundProperty } from '../core/types.js';
  import ComponentHost from '../core/ComponentHost.svelte';

  interface Props {
    props: Record<string, BoundProperty>;
    surface: SurfaceModel<ComponentApi>;
    componentId: string;
    dataContextPath: string;
    registry: ComponentRegistry;
    theme?: any;
  }

  let { props, surface, dataContextPath, registry }: Props = $props();

  const trigger = $derived(props.trigger?.value);
  const content = $derived(props.content?.value);

  let isOpen = $state(false);
  let dialogRef: HTMLDialogElement | undefined = $state();

  function openModal() {
    isOpen = true;
    // Use the native <dialog> API for proper a11y (focus trapping, Escape key, etc.)
    dialogRef?.showModal();
  }

  function closeModal() {
    isOpen = false;
    dialogRef?.close();
  }

  function handleDialogClose() {
    // Handles native Escape key close
    isOpen = false;
  }

  function handleBackdropClick(event: MouseEvent) {
    // Only close if clicking the backdrop, not the content
    if (event.target === dialogRef) {
      closeModal();
    }
  }
</script>

<div class="a2ui-modal">
  <button
    type="button"
    class="a2ui-modal-trigger"
    onclick={openModal}
    aria-haspopup="dialog"
  >
    {#if trigger}
      <ComponentHost
        {surface}
        componentId={trigger}
        {dataContextPath}
        {registry}
      />
    {/if}
  </button>

  <dialog
    bind:this={dialogRef}
    class="a2ui-modal-dialog"
    onclose={handleDialogClose}
    onclick={handleBackdropClick}
  >
    <div class="a2ui-modal-content">
      <button
        type="button"
        class="a2ui-modal-close"
        onclick={closeModal}
        aria-label="Close"
      >&times;</button>
      {#if content && isOpen}
        <ComponentHost
          {surface}
          componentId={content}
          {dataContextPath}
          {registry}
        />
      {/if}
    </div>
  </dialog>
</div>
