// renderers/react/src/v0_9/components/Text.tsx
import React, { memo } from 'react';
import type { A2UIComponentProps } from '../core/types.js';

/**
 * Text component — renders text content with an optional variant style.
 */
export const Text = memo(function Text({
  props,
}: A2UIComponentProps) {
  const text = props.text?.value ?? '';
  const variant = props.variant?.value ?? 'body';

  return (
    <span className={`a2ui-text a2ui-text--${variant}`}>
      {text}
    </span>
  );
});

// renderers/svelte/src/components/Text.svelte
<script lang="ts">
  import type { SurfaceModel, ComponentApi } from '@a2ui/web_core/v0_9';
  import type { ComponentRegistry, BoundProperty } from '../core/types.js';

  interface Props {
    props: Record<string, BoundProperty>;
    surface: SurfaceModel<ComponentApi>;
    componentId: string;
    dataContextPath: string;
    registry: ComponentRegistry;
  }

  let { props }: Props = $props();

  const text = $derived(props.text?.value ?? '');
  const variant = $derived(props.variant?.value ?? 'body');
</script>

<span class="a2ui-text {variant}">{text}</span>
