// renderers/lit/src/v0_9/catalogs/basic/components/Modal.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { html , nothing} from "lit";
import { customElement, query } from "lit/decorators.js";
import { A2uiLitElement } from "../../../base-element.js";
import { A2uiController } from "../../../adapter.js";
import { ModalApi } from "@a2ui/web_core/v0_9/basic_catalog";

@customElement("a2ui-modal")
export class A2uiLitModal extends A2uiLitElement<typeof ModalApi> {
  protected createController() { return new A2uiController(this, ModalApi); }
  @query("dialog") accessor dialog!: HTMLDialogElement;

  render() {
    const props = this.controller.props;
    if (!props) return nothing;

    return html`
      <div @click=${() => this.dialog?.showModal()}>
        ${props.trigger ? html`${this.renderNode(props.trigger)}` : nothing}
      </div>
      <dialog class="a2ui-modal" style="border: 1px solid #ccc; border-radius: 8px; padding: 24px; min-width: 300px;">
        <form method="dialog" style="text-align: right;"><button>×</button></form>
        ${props.content ? html`${this.renderNode(props.content)}` : nothing}
      </dialog>
    `;
  }
}

export const A2uiModal = {
  ...ModalApi,
  tagName: "a2ui-modal"
};

// renderers/react/src/v0_9/catalog/basic/components/Modal.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {useState} from 'react';
import {createReactComponent} from '../../../adapter';
import {ModalApi} from '@a2ui/web_core/v0_9/basic_catalog';

export const Modal = createReactComponent(ModalApi, ({props, buildChild}) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <>
      <div onClick={() => setIsOpen(true)} style={{display: 'inline-block'}}>
        {props.trigger ? buildChild(props.trigger) : null}
      </div>
      {isOpen && (
        <div
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0,0,0,0.5)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 1000,
          }}
          onClick={() => setIsOpen(false)}
        >
          <div
            style={{
              backgroundColor: '#fff',
              padding: '24px',
              borderRadius: '8px',
              maxWidth: '90%',
              maxHeight: '90%',
              overflow: 'auto',
              position: 'relative',
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <button
              onClick={() => setIsOpen(false)}
              style={{
                position: 'absolute',
                top: '8px',
                right: '8px',
                border: 'none',
                background: 'none',
                fontSize: '20px',
                cursor: 'pointer',
              }}
            >
              &times;
            </button>
            {props.content ? buildChild(props.content) : null}
          </div>
        </div>
      )}
    </>
  );
});
