// renderers/lit/src/v0_9/catalogs/basic/components/Video.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { html, nothing} from "lit";
import { customElement } from "lit/decorators.js";
import { A2uiLitElement } from "../../../base-element.js";
import { A2uiController } from "../../../adapter.js";
import { VideoApi } from "@a2ui/web_core/v0_9/basic_catalog";

@customElement("a2ui-video")
export class A2uiVideoElement extends A2uiLitElement<typeof VideoApi> {
  protected createController() { return new A2uiController(this, VideoApi); }

  render() {
    const props = this.controller.props;
    if (!props) return nothing;

    return html`<video src=${props.url} controls class="a2ui-video"></video>`;
  }
}

export const A2uiVideo = {
  ...VideoApi,
  tagName: "a2ui-video"
};

// renderers/react/src/v0_9/catalog/basic/components/Video.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import {createComponentImplementation} from '../../../adapter';
import {VideoApi} from '@a2ui/web_core/v0_9/basic_catalog';
import {getBaseLeafStyle, withWeight} from '../utils';

export const Video = createComponentImplementation(VideoApi, ({props}) => {
  const style: React.CSSProperties = {
    ...getBaseLeafStyle(),
    width: '100%',
    aspectRatio: '16/9',
  };

  return withWeight(<video src={props.url} controls style={style} />, props.weight);
});
