// renderers/react/src/v0_9/catalog/basic/components/Column.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {createComponentImplementation} from '../../../adapter';
import {ColumnApi} from '@a2ui/web_core/v0_9/basic_catalog';
import {ChildList} from './ChildList';
import {mapJustify, mapAlign, getWeightStyle, useBasicCatalogStyles} from '../utils';

export const Column = createComponentImplementation(ColumnApi, ({props}) => {
  useBasicCatalogStyles();
  return (
    <div
      style={{
        ...getWeightStyle(props.weight),
        display: 'flex',
        flexDirection: 'column',
        justifyContent: mapJustify(props.justify as any),
        alignItems: mapAlign(props.align as any),
        gap: 'var(--a2ui-column-gap, var(--a2ui-spacing-m))',
      }}
    >
      <ChildList childList={props.children} />
    </div>
  );
});

// renderers/lit/src/v0_9/catalogs/basic/components/Column.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { html, nothing} from "lit";
import { customElement } from "lit/decorators.js";
import { map } from "lit/directives/map.js";
import { styleMap } from "lit/directives/style-map.js";
import { A2uiLitElement } from "../../../base-element.js";
import { A2uiController } from "../../../adapter.js";
import { ColumnApi } from "@a2ui/web_core/v0_9/basic_catalog";

@customElement("a2ui-basic-column")
export class A2uiBasicColumnElement extends A2uiLitElement<typeof ColumnApi> {
  protected createController() { return new A2uiController(this, ColumnApi); }

  render() {
    const props = this.controller.props;
    if (!props) return nothing;

    const children = Array.isArray(props.children) ? props.children : [];
    const styles = { display: "flex", flexDirection: "column", flex: props.weight !== undefined ? String(props.weight) : "initial", gap: "8px" };
    
    return html`
      <div class="a2ui-column" style=${styleMap(styles as Record<string, string>)}>
        ${map(children, (child: any) => html`${this.renderNode(child)}`)}
      </div>
    `;
  }
}

export const A2uiColumn = {
  ...ColumnApi,
  tagName: "a2ui-basic-column"
};
