// renderers/svelte/src/components/AudioPlayer.svelte
<script lang="ts">
  import type { SurfaceModel, ComponentApi } from '@a2ui/web_core/v0_9';
  import type { ComponentRegistry, BoundProperty } from '../core/types.js';

  interface Props {
    props: Record<string, BoundProperty>;
    surface: SurfaceModel<ComponentApi>;
    componentId: string;
    dataContextPath: string;
    registry: ComponentRegistry;
  }

  let { props }: Props = $props();

  const url = $derived(props.url?.value ?? '');
  const description = $derived(props.description?.value ?? '');
</script>

<div class="a2ui-audio-player">
  {#if description}
    <span class="a2ui-audio-description">{description}</span>
  {/if}
  <audio class="a2ui-audio" src={url} controls></audio>
</div>

// renderers/react/src/v0_9/components/AudioPlayer.tsx
import React, { memo } from 'react';
import type { A2UIComponentProps } from '../core/types.js';

/**
 * AudioPlayer component — renders an audio element with optional description.
 */
export const AudioPlayer = memo(function AudioPlayer({
  props,
}: A2UIComponentProps) {
  const url = props.url?.value ?? '';
  const description = props.description?.value ?? '';

  return (
    <div className="a2ui-audio-player">
      {description && <span className="a2ui-audio-player__description">{description}</span>}
      <audio src={url} controls />
    </div>
  );
});
