// renderers/svelte/src/components/Button.svelte
<script lang="ts">
  import type { SurfaceModel, ComponentApi } from '@a2ui/web_core/v0_9';
  import type { ComponentRegistry, BoundProperty } from '../core/types.js';
  import ComponentHost from '../core/ComponentHost.svelte';
  import { dispatchAction } from '../core/use-component.svelte.js';

  interface Props {
    props: Record<string, BoundProperty>;
    surface: SurfaceModel<ComponentApi>;
    componentId: string;
    dataContextPath: string;
    registry: ComponentRegistry;
  }

  let { props, surface, componentId, dataContextPath, registry }: Props = $props();

  const variant = $derived(props.variant?.value ?? 'default');
  const child = $derived(props.child?.value);

  function handleClick() {
    dispatchAction(surface, props.action?.raw, componentId, dataContextPath);
  }
</script>

<button
  type={variant === 'primary' ? 'submit' : 'button'}
  class="a2ui-button {variant}"
  onclick={handleClick}
>
  {#if child}
    <ComponentHost
      {surface}
      componentId={child}
      {dataContextPath}
      {registry}
    />
  {/if}
</button>

// renderers/react/src/v0_9/components/Button.tsx
import React, { memo, useCallback } from 'react';
import type { A2UIComponentProps } from '../core/types.js';
import { ComponentHost } from '../core/ComponentHost.js';
import { dispatchAction } from '../core/useComponent.js';
import { useA2UI } from '../core/A2UIProvider.js';

/**
 * Button component — dispatches an action on click, renders a child component.
 */
export const Button = memo(function Button({
  props,
  surfaceId,
  componentId,
  dataContextPath,
  registry,
}: A2UIComponentProps) {
  const { surfaceGroup } = useA2UI();
  const surface = surfaceGroup.getSurface(surfaceId);

  const childId = props.child?.raw;
  const variant = props.variant?.value ?? 'default';

  const handleClick = useCallback(() => {
    if (surface) {
      dispatchAction(surface, props.action?.raw, componentId, dataContextPath);
    }
  }, [surface, props.action?.raw, componentId, dataContextPath]);

  if (!surface) return null;

  return (
    <button
      className={`a2ui-button a2ui-button--${variant}`}
      onClick={handleClick}
    >
      {childId && (
        <ComponentHost
          surface={surface}
          componentId={childId}
          dataContextPath={dataContextPath}
          registry={registry}
        />
      )}
    </button>
  );
});
