// renderers/svelte/src/components/CheckBox.svelte
<script lang="ts">
  import type { SurfaceModel, ComponentApi } from '@a2ui/web_core/v0_9';
  import type { ComponentRegistry, BoundProperty } from '../core/types.js';

  interface Props {
    props: Record<string, BoundProperty>;
    surface: SurfaceModel<ComponentApi>;
    componentId: string;
    dataContextPath: string;
    registry: ComponentRegistry;
  }

  let { props }: Props = $props();

  const label = $derived(props.label?.value ?? '');
  const checked = $derived(!!props.value?.value);

  function handleChange(event: Event) {
    const target = event.target as HTMLInputElement;
    props.value?.onUpdate(target.checked);
  }
</script>

<label class="a2ui-checkbox">
  <input
    type="checkbox"
    class="a2ui-checkbox-input"
    checked={checked}
    onchange={handleChange}
  />
  <span class="a2ui-checkbox-label">{label}</span>
</label>

// renderers/react/src/v0_9/components/CheckBox.tsx
import React, { memo, useCallback } from 'react';
import type { A2UIComponentProps } from '../core/types.js';

/**
 * CheckBox component — checkbox with label and two-way boolean binding.
 */
export const CheckBox = memo(function CheckBox({
  props,
}: A2UIComponentProps) {
  const label = props.label?.value ?? '';
  const value = props.value?.value ?? false;

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      props.value?.onUpdate(e.target.checked);
    },
    [props.value],
  );

  return (
    <label className="a2ui-checkbox">
      <input
        className="a2ui-checkbox__input"
        type="checkbox"
        checked={!!value}
        onChange={handleChange}
      />
      <span className="a2ui-checkbox__label">{label}</span>
    </label>
  );
});
