// renderers/lit/src/v0_9/standard_catalog/components/image.ts
import { html, TemplateResult } from 'lit';
import { ImageComponent } from '@a2ui/web_core/v0_9';

export const litImage = new ImageComponent<TemplateResult>(
    ({ url, fit, variant }) => {
        // Map 'fit' to object-fit CSS property
        const styleMap = {
            'contain': 'object-fit: contain;',
            'cover': 'object-fit: cover;',
            'fill': 'object-fit: fill;',
            'none': 'object-fit: none;',
            'scale-down': 'object-fit: scale-down;',
        };
        const style = fit ? styleMap[fit] : '';
        const className = variant ? `a2ui-image-${variant}` : 'a2ui-image';
        
        return html`<img src="${url}" style="${style}" class="${className}" alt="" />`;
    }
);

// renderers/react/src/v0_9/components/Image.tsx
import React, { memo } from 'react';
import type { A2UIComponentProps } from '../core/types.js';

/**
 * Image component — renders an img element with url, fit, and variant.
 */
export const Image = memo(function Image({
  props,
}: A2UIComponentProps) {
  const url = props.url?.value ?? '';
  const fit = props.fit?.value ?? 'fill';
  const variant = props.variant?.value ?? 'mediumFeature';

  const fitMap: Record<string, string> = {
    contain: 'contain',
    cover: 'cover',
    fill: 'fill',
    none: 'none',
    scaleDown: 'scale-down',
  };

  return (
    <img
      className={`a2ui-image a2ui-image--${variant}`}
      src={url}
      alt=""
      style={{ objectFit: (fitMap[fit] ?? 'fill') as React.CSSProperties['objectFit'] }}
    />
  );
});
