// renderers/svelte/src/components/Row.svelte
<script lang="ts">
  import type { SurfaceModel, ComponentApi } from '@a2ui/web_core/v0_9';
  import type { ComponentRegistry, BoundProperty } from '../core/types.js';
  import ComponentHost from '../core/ComponentHost.svelte';

  interface Props {
    props: Record<string, BoundProperty>;
    surface: SurfaceModel<ComponentApi>;
    componentId: string;
    dataContextPath: string;
    registry: ComponentRegistry;
  }

  let { props, surface, dataContextPath, registry }: Props = $props();

  const justify = $derived(props.justify?.value ?? 'start');
  const align = $derived(props.align?.value ?? 'stretch');

  const children = $derived.by(() => {
    const raw = props.children?.value;
    return Array.isArray(raw) ? raw : [];
  });

  const isRepeating = $derived(!!props.children?.raw?.componentId);
  const templateId = $derived(props.children?.raw?.componentId);

  function getNormalizedPath(path: string, dcp: string, index: number): string {
    let normalized = path || '';
    if (!normalized.startsWith('/')) {
      const base = dcp === '/' ? '' : dcp;
      normalized = `${base}/${normalized}`;
    }
    if (normalized.endsWith('/')) normalized = normalized.slice(0, -1);
    return `${normalized}/${index}`;
  }
</script>

<div
  class="a2ui-row"
  style:display="flex"
  style:flex-direction="row"
  style:width="100%"
  style:gap="4px"
  style:justify-content={justify}
  style:align-items={align}
>
  {#if !isRepeating}
    {#each children as childId (childId)}
      <ComponentHost
        {surface}
        componentId={childId}
        {dataContextPath}
        {registry}
      />
    {/each}
  {:else}
    {#each children as _, i (i)}
      <ComponentHost
        {surface}
        componentId={templateId}
        dataContextPath={getNormalizedPath(props.children?.raw?.path, dataContextPath, i)}
        {registry}
      />
    {/each}
  {/if}
</div>

// renderers/react/src/v0_9/components/Row.tsx
import React, { memo } from 'react';
import type { A2UIComponentProps } from '../core/types.js';
import { ComponentHost } from '../core/ComponentHost.js';
import { getNormalizedPath } from '../core/useComponent.js';
import { useA2UI } from '../core/A2UIProvider.js';

/**
 * Row component — arranges children horizontally using flexbox.
 */
export const Row = memo(function Row({
  props,
  surfaceId,
  dataContextPath,
  registry,
}: A2UIComponentProps) {
  const { surfaceGroup } = useA2UI();
  const surface = surfaceGroup.getSurface(surfaceId);

  const justify = props.justify?.value ?? 'start';
  const align = props.align?.value ?? 'stretch';
  const childrenRaw = props.children?.raw;
  const childrenValue = props.children?.value;

  if (!surface) return null;

  const justifyMap: Record<string, string> = {
    start: 'flex-start',
    center: 'center',
    end: 'flex-end',
    spaceBetween: 'space-between',
    spaceAround: 'space-around',
    spaceEvenly: 'space-evenly',
    stretch: 'stretch',
  };

  const alignMap: Record<string, string> = {
    start: 'flex-start',
    center: 'center',
    end: 'flex-end',
    stretch: 'stretch',
  };

  const style: React.CSSProperties = {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: justifyMap[justify] ?? 'flex-start',
    alignItems: alignMap[align] ?? 'stretch',
  };

  // Repeating template: { componentId, path }
  if (childrenRaw && typeof childrenRaw === 'object' && 'componentId' in childrenRaw) {
    const items = Array.isArray(childrenValue) ? childrenValue : [];
    return (
      <div className="a2ui-row" style={style}>
        {items.map((_: any, index: number) => (
          <ComponentHost
            key={index}
            surface={surface}
            componentId={childrenRaw.componentId}
            dataContextPath={getNormalizedPath(childrenRaw.path, dataContextPath, index)}
            registry={registry}
          />
        ))}
      </div>
    );
  }

  // Static array of component IDs
  const childIds = Array.isArray(childrenRaw) ? childrenRaw : [];
  return (
    <div className="a2ui-row" style={style}>
      {childIds.map((childId: string) => (
        <ComponentHost
          key={childId}
          surface={surface}
          componentId={childId}
          dataContextPath={dataContextPath}
          registry={registry}
        />
      ))}
    </div>
  );
});
