// renderers/svelte/src/components/Tabs.svelte
<script lang="ts">
  import type { SurfaceModel, ComponentApi } from '@a2ui/web_core/v0_9';
  import type { ComponentRegistry, BoundProperty } from '../core/types.js';
  import ComponentHost from '../core/ComponentHost.svelte';

  interface Props {
    props: Record<string, BoundProperty>;
    surface: SurfaceModel<ComponentApi>;
    componentId: string;
    dataContextPath: string;
    registry: ComponentRegistry;
  }

  let { props, surface, dataContextPath, registry }: Props = $props();

  const tabs = $derived(props.tabs?.value ?? []);

  let activeTabIndex = $state(0);

  const activeTab = $derived(tabs[activeTabIndex]);

  function setActiveTab(index: number) {
    activeTabIndex = index;
  }
</script>

<div class="a2ui-tabs">
  <div class="a2ui-tab-bar">
    {#each tabs as tab, i (i)}
      <button
        class="a2ui-tab-button"
        class:active={activeTabIndex === i}
        onclick={() => setActiveTab(i)}
      >
        {tab.label ?? tab.title ?? ''}
      </button>
    {/each}
  </div>
  {#if activeTab}
    <div class="a2ui-tab-content">
      <ComponentHost
        {surface}
        componentId={activeTab.content ?? activeTab.child}
        {dataContextPath}
        {registry}
      />
    </div>
  {/if}
</div>

// renderers/react/src/v0_9/components/Tabs.tsx
import React, { memo, useState } from 'react';
import type { A2UIComponentProps } from '../core/types.js';
import { ComponentHost } from '../core/ComponentHost.js';
import { useA2UI } from '../core/A2UIProvider.js';

/**
 * Tabs component — tab navigation with switchable content panels.
 */
export const Tabs = memo(function Tabs({
  props,
  surfaceId,
  dataContextPath,
  registry,
}: A2UIComponentProps) {
  const { surfaceGroup } = useA2UI();
  const surface = surfaceGroup.getSurface(surfaceId);
  const [selectedIndex, setSelectedIndex] = useState(0);

  const tabs = props.tabs?.value;

  if (!surface || !Array.isArray(tabs) || tabs.length === 0) return null;

  const safeIndex = Math.min(selectedIndex, tabs.length - 1);

  return (
    <div className="a2ui-tabs">
      <div className="a2ui-tabs__buttons" role="tablist">
        {tabs.map((tab: any, index: number) => (
          <button
            key={index}
            role="tab"
            className={`a2ui-tabs__tab ${index === safeIndex ? 'a2ui-tabs__tab--selected' : ''}`}
            aria-selected={index === safeIndex}
            disabled={index === safeIndex}
            onClick={() => setSelectedIndex(index)}
          >
            {tab.title}
          </button>
        ))}
      </div>
      <div className="a2ui-tabs__content" role="tabpanel">
        {tabs[safeIndex]?.child && (
          <ComponentHost
            surface={surface}
            componentId={tabs[safeIndex].child}
            dataContextPath={dataContextPath}
            registry={registry}
          />
        )}
      </div>
    </div>
  );
});
