// renderers/svelte/src/components/Video.svelte
<script lang="ts">
  import type { SurfaceModel, ComponentApi } from '@a2ui/web_core/v0_9';
  import type { ComponentRegistry, BoundProperty } from '../core/types.js';

  interface Props {
    props: Record<string, BoundProperty>;
    surface: SurfaceModel<ComponentApi>;
    componentId: string;
    dataContextPath: string;
    registry: ComponentRegistry;
  }

  let { props }: Props = $props();

  const url = $derived(props.url?.value ?? '');
</script>

<!-- svelte-ignore a11y_media_has_caption -->
<video class="a2ui-video" src={url} controls>
  <track kind="captions" />
</video>

// renderers/react/src/v0_9/components/Video.tsx
import React, { memo } from 'react';
import type { A2UIComponentProps } from '../core/types.js';

/**
 * Video component — renders a video element with controls.
 */
export const Video = memo(function Video({
  props,
}: A2UIComponentProps) {
  const url = props.url?.value ?? '';

  return (
    <video className="a2ui-video" src={url} controls />
  );
});
