// samples/client/react/projects/gallery/src/App.tsx
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { useState } from "react";
import { Library } from "./features/Library";
import { Gallery } from "./features/Gallery";

type ViewType = "library" | "gallery";

function App() {
  const [currentView, setCurrentView] = useState<ViewType>("library");

  return (
    <div className="app-container">
      <div className="main-sidebar">
        <h1 className="app-title">A2UI Gallery</h1>
        <nav className="nav-buttons">
          <button
            className={`nav-btn ${currentView === "library" ? "active" : ""}`}
            onClick={() => setCurrentView("library")}
          >
            <span className="material-icons">widgets</span>
            Library
          </button>
          <button
            className={`nav-btn ${currentView === "gallery" ? "active" : ""}`}
            onClick={() => setCurrentView("gallery")}
          >
            <span className="material-icons">collections</span>
            Gallery
          </button>
        </nav>
      </div>
      <div className="content-area">
        {currentView === "library" ? <Library /> : <Gallery />}
      </div>
    </div>
  );
}

export default App;

// samples/client/angular/projects/gallery/src/app/app.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { LibraryComponent } from './features/library/library.component';
import { GalleryComponent } from './features/gallery/gallery.component';

@Component({
  selector: 'app-root',
  templateUrl: './app.html',
  styleUrl: './app.css',
  imports: [LibraryComponent, GalleryComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class App {
  readonly currentView = signal<'library' | 'gallery'>('library');

  setView(view: 'library' | 'gallery') {
    this.currentView.set(view);
  }
}
