// samples/client/react/projects/a2a-chat-canvas/src/components/Chat.tsx
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import React from "react";
import { ChatHistory } from "./ChatHistory";
import { InputArea } from "./InputArea";
import { MessageDecoratorProps } from "../types";

interface ChatProps {
  emptyHistoryContent?: React.ReactNode;
  messageDecorator?: React.ComponentType<MessageDecoratorProps>;
  className?: string;
}

/**
 * Chat component that combines the chat history and input area.
 */
export function Chat({
  emptyHistoryContent,
  messageDecorator,
  className,
}: ChatProps) {
  return (
    <div className={`chat ${className || ""}`}>
      <ChatHistory
        emptyContent={emptyHistoryContent}
        messageDecorator={messageDecorator}
        className="chat-history-container"
      />
      <InputArea className="chat-input-container" />
    </div>
  );
}

// samples/client/angular/projects/a2a_chat_canvas/src/lib/components/chat/chat.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ChatHistory } from '@a2a-chat-canvas/components/chat/chat_history/chat-history';
import { MessageDecorator } from '@a2a-chat-canvas/components/chat/chat_history/message_decorator/types';
import { InputArea } from '@a2a-chat-canvas/components/chat/input_area/input-area';
import { ChatService } from '@a2a-chat-canvas/services/chat-service';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
  TemplateRef,
} from '@angular/core';

/**
 * Main component for the chat interface.
 * It orchestrates the chat history display and the input area.
 */
@Component({
  selector: 'chat',
  templateUrl: './chat.html',
  styleUrl: './chat.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ChatHistory, InputArea],
})
export class Chat {
  readonly emptyHistoryTemplate = input<TemplateRef<unknown>>();
  /** Optional function to provide a custom message decorator component. */
  readonly messageDecorator = input<MessageDecorator>();

  /** Service for managing chat interactions. */
  private readonly chatService = inject(ChatService);

  /** The chat message history. */
  readonly history = computed(() => this.chatService.history());
}
