// samples/client/react/projects/rizzcharts/src/components/Chart.tsx
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { useState, useMemo, useCallback } from "react";
import { Types, Primitives, useDataBinding } from "@a2ui/react";
import {
  Chart as ChartJS,
  ArcElement,
  Tooltip,
  Legend,
  ChartData,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
} from "chart.js";
import ChartDataLabels from "chartjs-plugin-datalabels";
import { Pie, Doughnut, Bar } from "react-chartjs-2";
import "./Chart.css";

ChartJS.register(
  ArcElement,
  Tooltip,
  Legend,
  ChartDataLabels,
  CategoryScale,
  LinearScale,
  BarElement,
  Title
);

// Chart.js default color palette
const CHART_COLORS = [
  "rgba(255, 99, 132, 0.8)",   // Red
  "rgba(54, 162, 235, 0.8)",   // Blue
  "rgba(255, 206, 86, 0.8)",   // Yellow
  "rgba(75, 192, 192, 0.8)",   // Teal
  "rgba(153, 102, 255, 0.8)",  // Purple
  "rgba(255, 159, 64, 0.8)",   // Orange
  "rgba(199, 199, 199, 0.8)",  // Grey
  "rgba(83, 102, 255, 0.8)",   // Indigo
  "rgba(255, 99, 255, 0.8)",   // Pink
  "rgba(99, 255, 132, 0.8)",   // Green
];

const CHART_BORDER_COLORS = [
  "rgba(255, 99, 132, 1)",
  "rgba(54, 162, 235, 1)",
  "rgba(255, 206, 86, 1)",
  "rgba(75, 192, 192, 1)",
  "rgba(153, 102, 255, 1)",
  "rgba(255, 159, 64, 1)",
  "rgba(199, 199, 199, 1)",
  "rgba(83, 102, 255, 1)",
  "rgba(255, 99, 255, 1)",
  "rgba(99, 255, 132, 1)",
];

interface ChartProperties {
  type?: Primitives.StringValue;
  title?: Primitives.StringValue;
  chartData?: Primitives.StringValue;
}

interface ChartProps {
  node: Types.AnyComponentNode & { properties: ChartProperties };
  surfaceId: string;
}

export function Chart({ node, surfaceId }: ChartProps) {
  const { resolveString, getValue } = useDataBinding(node, surfaceId);
  const [selectedCategory, setSelectedCategory] = useState<string>("root");

  const properties = node.properties;
  const chartType = resolveString(properties.type ?? null) ?? "pie";
  const title = resolveString(properties.title ?? null);
  const chartDataPath = properties.chartData?.path;

  const chartDataMap = useMemo(() => {
    if (!chartDataPath) return null;

    const dataMap = new Map<string, ChartData<"pie" | "bar", number[], string>>();
    const labels: string[] = [];
    const values: number[] = [];

    for (let index = 0; index < 500; index++) {
      const itemPrefix = `${chartDataPath}[${index}]`;
      const label = getValue(`${itemPrefix}.label`);
      const value = getValue(`${itemPrefix}.value`);

      if (label === null || value === null) break;

      labels.push(String(label));
      values.push(Number(value));

      const drilldownLabels: string[] = [];
      const drilldownValues: number[] = [];
      const drilldownPathPrefix = `${itemPrefix}.drillDown`;

      for (let jIndex = 0; jIndex < 500; jIndex++) {
        const drilldownItemPrefix = `${drilldownPathPrefix}[${jIndex}]`;
        const drilldownLabel = getValue(`${drilldownItemPrefix}.label`);
        const drilldownValue = getValue(`${drilldownItemPrefix}.value`);

        if (drilldownLabel === null || drilldownValue === null) break;

        drilldownLabels.push(String(drilldownLabel));
        drilldownValues.push(Number(drilldownValue));
      }

      if (drilldownLabels.length > 0) {
        dataMap.set(String(label), {
          labels: drilldownLabels,
          datasets: [{
            data: drilldownValues,
            backgroundColor: CHART_COLORS.slice(0, drilldownValues.length),
            borderColor: CHART_BORDER_COLORS.slice(0, drilldownValues.length),
            borderWidth: 2,
          }],
        });
      }
    }

    dataMap.set("root", {
      labels,
      datasets: [{
        data: values,
        backgroundColor: CHART_COLORS.slice(0, values.length),
        borderColor: CHART_BORDER_COLORS.slice(0, values.length),
        borderWidth: 2,
      }],
    });

    return dataMap;
  }, [chartDataPath, getValue]);

  const currentData = useMemo(() => {
    if (!chartDataMap) return null;
    return chartDataMap.get(selectedCategory) ?? null;
  }, [chartDataMap, selectedCategory]);

  const isDrillDown = selectedCategory !== "root";

  const handleChartClick = useCallback(
    (_: unknown, elements: Array<{ index: number }>) => {
      if (!elements.length || isDrillDown) return;

      const clickedIndex = elements[0].index;
      const clickedLabel = currentData?.labels?.[clickedIndex];

      if (clickedLabel && chartDataMap?.has(String(clickedLabel))) {
        setSelectedCategory(String(clickedLabel));
      }
    },
    [currentData, chartDataMap, isDrillDown]
  );

  const handleRestoreOriginal = useCallback(() => {
    setSelectedCategory("root");
  }, []);

  const isPieOrDoughnut = chartType === "pie" || chartType === "doughnut";

  const chartOptions = useMemo(
    () => ({
      responsive: true,
      maintainAspectRatio: true,
      plugins: {
        legend: {
          display: true,
          position: isPieOrDoughnut ? "right" as const : "top" as const,
          labels: {
            color: "#94a3b8",
            font: { size: 14 },
          },
          onClick: isPieOrDoughnut
            ? (_: unknown, legendItem: { text: string }) => {
                if (!isDrillDown && chartDataMap?.has(legendItem.text)) {
                  setSelectedCategory(legendItem.text);
                }
              }
            : undefined,
        },
        datalabels: isPieOrDoughnut
          ? {
              formatter: (value: number, ctx: any) => {
                const dataset = ctx.chart.data.datasets[0];
                const total = dataset.data.reduce((a: number, b: number) => a + b, 0);
                const percentage = ((value / total) * 100).toFixed(1);
                return `${percentage}%`;
              },
              color: "white",
              font: { size: 14, weight: "bold" as const },
            }
          : {
              display: false,
            },
      },
      scales: isPieOrDoughnut
        ? undefined
        : {
            x: {
              grid: { color: "rgba(255, 255, 255, 0.1)" },
              ticks: { color: "#94a3b8" },
            },
            y: {
              grid: { color: "rgba(255, 255, 255, 0.1)" },
              ticks: { color: "#94a3b8" },
              beginAtZero: true,
            },
          },
      onClick: isPieOrDoughnut ? handleChartClick : undefined,
    }),
    [handleChartClick, isDrillDown, chartDataMap, isPieOrDoughnut]
  );

  if (!currentData) {
    return (
      <div className="chart-box-container">
        <div className="chart-header">
          <h2>{title ?? "Chart"}</h2>
        </div>
        <div className="chart-container">
          <p>No chart data available</p>
        </div>
      </div>
    );
  }

  return (
    <div className="chart-box-container">
      <div className="chart-header">
        <div>
          <h2>{title ?? "Chart"}</h2>
          {isDrillDown && <h3>{selectedCategory}</h3>}
        </div>
        <div className="chart-actions">
          <button className="icon-button" title="Download">
            <DownloadIcon />
          </button>
          <button className="icon-button" title="Share">
            <ShareIcon />
          </button>
        </div>
      </div>
      <div className="chart-container">
        {isDrillDown && (
          <button className="back-button" onClick={handleRestoreOriginal}>
            <BackIcon />
          </button>
        )}
        {chartType === "bar" ? (
          <Bar data={currentData as any} options={chartOptions as any} />
        ) : chartType === "doughnut" ? (
          <Doughnut data={currentData as any} options={chartOptions as any} />
        ) : (
          <Pie data={currentData as any} options={chartOptions as any} />
        )}
      </div>
    </div>
  );
}

function DownloadIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
      <path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z" />
    </svg>
  );
}

function ShareIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
      <path d="M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92s2.92-1.31 2.92-2.92-1.31-2.92-2.92-2.92z" />
    </svg>
  );
}

function BackIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
      <path d="M20 11H7.83l5.59-5.59L12 4l-8 8 8 8 1.41-1.41L7.83 13H20v-2z" />
    </svg>
  );
}

// samples/client/lit/component_gallery/ui/custom-components/chart.ts
/**
 * A2UI Custom Chart Component — Lit implementation of the RIZZcharts Chart
 * contract.
 *
 * Follows the same data resolution pattern as the OrgChart Lit sample:
 * properties may be plain values or { path: string } references resolved
 * via processor.getData().
 *
 * Supports chart types: pie, doughnut, bar.
 * Supports one-level drill-down: click a wedge/bar or legend label to view
 * sub-data, then click the back button to return to the root view.
 */

import {Root} from '@a2ui/lit/ui';
import {html, css, nothing} from 'lit';
import {property} from 'lit/decorators.js';
import {
  Chart as ChartJS,
  ArcElement,
  BarElement,
  BarController,
  PieController,
  DoughnutController,
  CategoryScale,
  LinearScale,
  Tooltip,
  Legend,
  Title,
  type ChartConfiguration,
} from 'chart.js';
import ChartDataLabels from 'chartjs-plugin-datalabels';

// Register the Chart.js components we need (controllers + elements + plugins)
ChartJS.register(
  PieController,
  DoughnutController,
  BarController,
  ArcElement,
  BarElement,
  CategoryScale,
  LinearScale,
  Tooltip,
  Legend,
  Title,
  ChartDataLabels
);

// Palette for chart segments
const PALETTE = [
  '#4285F4', // blue
  '#EA4335', // red
  '#FBBC04', // yellow
  '#34A853', // green
  '#FF6D01', // orange
  '#46BDC6', // teal
  '#7B61FF', // purple
  '#F538A0', // pink
  '#00ACC1', // cyan
  '#8D6E63', // brown
];

interface ChartDataItem {
  label: string;
  value: number;
  drillDown?: ChartDataItem[];
}

/** Pre-computed labels + values for a single chart view. */
interface ChartView {
  labels: string[];
  values: number[];
}

export class ChartComponent extends Root {
  // Properties set by renderCustomComponent via el[prop] = val.
  @property({attribute: false}) accessor chartType: string = 'pie';
  @property({attribute: false}) accessor chartTitle: string = '';
  @property({attribute: false}) accessor chartData: unknown = null;

  private chartInstance: ChartJS | null = null;
  private selectedCategory: string = 'root';

  private get isDrillDown(): boolean {
    return this.selectedCategory !== 'root';
  }

  static styles = [
    ...Root.styles,
    css`
      :host {
        display: block;
        flex: var(--weight);
        padding: 16px;
      }

      .chart-box {
        background: light-dark(var(--n-98, #fafafa), var(--n-10, #1a1a1a));
        border: 1px solid
          light-dark(var(--n-90, #e0e0e0), var(--n-25, #3a3a3a));
        border-radius: 12px;
        padding: 24px;
        max-width: 700px;
        margin: 0 auto;
      }

      .chart-header {
        margin: 0 0 16px 0;
      }

      .chart-heading {
        font-size: 20px;
        font-weight: 600;
        margin: 0;
        color: light-dark(var(--n-10, #1a1a1a), var(--n-90, #e0e0e0));
      }

      .chart-subtitle {
        font-size: 16px;
        font-weight: 500;
        margin: 4px 0 0 0;
        color: light-dark(var(--n-30, #555), var(--n-70, #b0b0b0));
      }

      .back-btn {
        display: inline-flex;
        align-items: center;
        gap: 4px;
        background: none;
        border: 1px solid light-dark(var(--n-80, #ccc), var(--n-30, #444));
        border-radius: 6px;
        padding: 4px 12px;
        margin-bottom: 12px;
        cursor: pointer;
        font-size: 13px;
        color: light-dark(var(--n-20, #333), var(--n-80, #ccc));
      }

      .back-btn:hover {
        background: light-dark(var(--n-95, #f0f0f0), var(--n-15, #252525));
      }

      .chart-canvas-wrapper {
        position: relative;
        width: 100%;
        max-height: 400px;
      }

      canvas {
        width: 100% !important;
        max-height: 400px;
      }

      .no-data {
        text-align: center;
        padding: 40px;
        color: light-dark(var(--n-40, #888), var(--n-60, #999));
        font-style: italic;
      }
    `,
  ];

  disconnectedCallback() {
    super.disconnectedCallback();
    this.destroyChart();
  }

  updated() {
    this.buildChart();
  }

  // ---------------------------------------------------------------------------
  // Data resolution
  // ---------------------------------------------------------------------------

  private resolveStringProp(val: unknown): string {
    if (!val) return '';
    if (typeof val === 'string') return val;
    const obj = val as Record<string, unknown>;
    if (obj.literalString) return String(obj.literalString);
    if (obj.path && this.processor) {
      const resolved = this.processor.getData(
        this.component,
        String(obj.path),
        this.surfaceId ?? 'default'
      );
      return typeof resolved === 'string' ? resolved : '';
    }
    return '';
  }

  private resolveChartData(): ChartDataItem[] {
    let raw: unknown = this.chartData;

    // Resolve path reference (same pattern as OrgChart)
    if (
      raw &&
      typeof raw === 'object' &&
      'path' in (raw as Record<string, unknown>)
    ) {
      const pathObj = raw as {path: string};
      if (this.processor) {
        raw = this.processor.getData(
          this.component,
          pathObj.path,
          this.surfaceId ?? 'default'
        );
      }
    }

    // Model processor may return Map — normalize to Array
    if (raw instanceof Map) {
      const entries = Array.from(
        raw.entries() as IterableIterator<[string, unknown]>
      );
      entries.sort((a, b) => parseInt(a[0], 10) - parseInt(b[0], 10));
      raw = entries.map((e) => e[1]);
    }

    if (!Array.isArray(raw)) return [];

    return (raw as unknown[]).map((item) => {
      const getVal = (k: string): unknown => {
        if (item instanceof Map) return item.get(k);
        return (item as Record<string, unknown>)?.[k];
      };

      // Resolve drillDown sub-array (may also be a Map from the processor)
      let drillDown: ChartDataItem[] | undefined;
      let rawDrill = getVal('drillDown');
      if (rawDrill instanceof Map) {
        const entries = Array.from(
          rawDrill.entries() as IterableIterator<[string, unknown]>
        );
        entries.sort(
          (a, b) => parseInt(a[0], 10) - parseInt(b[0], 10)
        );
        rawDrill = entries.map((e) => e[1]);
      }
      if (Array.isArray(rawDrill) && rawDrill.length > 0) {
        drillDown = (rawDrill as unknown[]).map((sub) => {
          const subVal = (k: string): unknown => {
            if (sub instanceof Map) return sub.get(k);
            return (sub as Record<string, unknown>)?.[k];
          };
          return {
            label: String(subVal('label') ?? ''),
            value: Number(subVal('value') ?? 0),
          };
        });
      }

      return {
        label: String(getVal('label') ?? ''),
        value: Number(getVal('value') ?? 0),
        ...(drillDown ? {drillDown} : {}),
      };
    });
  }

  // ---------------------------------------------------------------------------
  // Drill-down map
  // ---------------------------------------------------------------------------

  /**
   * Build a Map of chart views keyed by category label.
   * "root" -> root-level data; each label with drillDown -> sub-data.
   */
  private buildDrillDownMap(
    items: ChartDataItem[]
  ): Map<string, ChartView> {
    const viewMap = new Map<string, ChartView>();

    viewMap.set('root', {
      labels: items.map((d) => d.label),
      values: items.map((d) => d.value),
    });

    for (const item of items) {
      if (item.drillDown && item.drillDown.length > 0) {
        viewMap.set(item.label, {
          labels: item.drillDown.map((d) => d.label),
          values: item.drillDown.map((d) => d.value),
        });
      }
    }

    return viewMap;
  }

  // ---------------------------------------------------------------------------
  // Chart lifecycle
  // ---------------------------------------------------------------------------

  private destroyChart() {
    if (this.chartInstance) {
      this.chartInstance.destroy();
      this.chartInstance = null;
    }
  }

  private restoreRoot() {
    this.selectedCategory = 'root';
    this.requestUpdate();
  }

  private buildChart() {
    const canvas = this.renderRoot?.querySelector('canvas') as
      | HTMLCanvasElement
      | undefined;
    if (!canvas) return;

    const items = this.resolveChartData();
    if (items.length === 0) return;

    const drillDownMap = this.buildDrillDownMap(items);
    const view = drillDownMap.get(this.selectedCategory);
    if (!view) return;

    const {labels, values} = view;
    const colors = labels.map(
      (_, i) => PALETTE[i % PALETTE.length]
    );

    this.destroyChart();

    const ct =
      (this.chartType || 'pie') as 'pie' | 'doughnut' | 'bar';
    const isPieType = ct === 'pie' || ct === 'doughnut';

    const config: ChartConfiguration = {
      type: isPieType ? ct : 'bar',
      data: {
        labels,
        datasets: [
          {
            data: values,
            backgroundColor: colors,
            borderColor: isPieType
              ? colors.map(() => 'rgba(255,255,255,0.8)')
              : colors,
            borderWidth: isPieType ? 2 : 1,
          },
        ],
      },
      options: {
        responsive: true,
        maintainAspectRatio: true,
        // Wedge / bar click -> drill down
        onClick: (_event, elements) => {
          if (!elements.length || this.isDrillDown) return;
          const index = elements[0].index;
          const label = labels[index];
          if (label && drillDownMap.has(label)) {
            this.selectedCategory = label;
            this.requestUpdate();
          }
        },
        plugins: {
          legend: {
            display: isPieType,
            position: 'right',
            labels: {font: {size: 13}},
            // Legend click -> drill down (pie/doughnut only)
            onClick: (_e, legendItem) => {
              if (this.isDrillDown) return;
              const label = legendItem.text;
              if (label && drillDownMap.has(label)) {
                this.selectedCategory = label;
                this.requestUpdate();
              }
            },
          },
          title: {display: false},
          tooltip: {
            callbacks: {
              label: (ctx) => {
                const val = ctx.parsed;
                const num =
                  typeof val === 'number'
                    ? val
                    : ((val as unknown as Record<string, number>)
                        .y ?? val);
                if (isPieType) {
                  const total = (
                    ctx.dataset.data as number[]
                  ).reduce((a, b) => a + (b as number), 0);
                  const pct = (
                    ((num as number) / total) *
                    100
                  ).toFixed(1);
                  return `${ctx.label}: ${(num as number).toLocaleString()} (${pct}%)`;
                }
                return `${ctx.label}: ${(num as number).toLocaleString()}`;
              },
            },
          },
          // On-wedge percentage labels (pie/doughnut only)
          datalabels: isPieType
            ? {
                // tslint:disable-next-line:no-any
                // Chart.js datalabels plugin context type
                formatter: (value: number, ctx: any) => {
                  const total = (
                    ctx.chart.data.datasets[0].data as number[]
                  ).reduce((a, b) => a + b, 0);
                  return `${((value / total) * 100).toFixed(1)}%`;
                },
                color: 'white',
                font: {size: 14},
              }
            : {display: false},
        },
        ...(isPieType
          ? {}
          : {
              scales: {
                y: {
                  beginAtZero: true,
                  ticks: {font: {size: 12}},
                },
                x: {
                  ticks: {font: {size: 12}, maxRotation: 45},
                },
              },
            }),
      },
    };

    this.chartInstance = new ChartJS(canvas, config);
  }

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------

  render() {
    const heading = this.resolveStringProp(this.chartTitle);
    const items = this.resolveChartData();

    if (items.length === 0) {
      return html`<div class="chart-box">
        <div class="no-data">No chart data available</div>
      </div>`;
    }

    return html`
      <div class="chart-box">
        <div class="chart-header">
          ${heading
            ? html`<h2 class="chart-heading">${heading}</h2>`
            : nothing}
          ${this.isDrillDown
            ? html`<h3 class="chart-subtitle">
                ${this.selectedCategory}
              </h3>`
            : nothing}
        </div>
        ${this.isDrillDown
          ? html`<button
              class="back-btn"
              @click=${this.restoreRoot}
            >
              \u2190 Back
            </button>`
          : nothing}
        <div class="chart-canvas-wrapper">
          <canvas></canvas>
        </div>
      </div>
    `;
  }
}
