// renderers/react/src/components/catalog/List.tsx
import React from 'react';
import { Types } from '@a2ui/lit/0.8';
import { CatalogComponentProps } from './index';
import { ChildRenderer } from '../Renderer';

export function List({ surfaceId, component }: CatalogComponentProps) {
  const node = component as Types.ListNode;
  const { direction = 'vertical', children } = node.properties;

  const style: React.CSSProperties = {
    display: 'flex',
    flexDirection: direction === 'horizontal' ? 'row' : 'column',
    gap: '8px',
    overflow: 'auto',
    flex: component.weight ?? 'initial',
  };

  return (
    <div id={component.id} style={style}>
      <ChildRenderer surfaceId={surfaceId} children={children} />
    </div>
  );
}

// renderers/lit/src/v0_9/standard_catalog/components/list.ts
import { html, TemplateResult } from 'lit';
import { ListComponent } from '@a2ui/web_core/v0_9';

export const litList = new ListComponent<TemplateResult>(
  ({ children, direction }) => {
    const style = direction === 'horizontal'
      ? 'display: flex; flex-direction: row; overflow-x: auto;'
      : 'display: flex; flex-direction: column;';
    return html`
            <div class="a2ui-list" style="${style}">
                ${children}
            </div>
        `;
  }
);
