// renderers/react/src/v0_9/components/TextField.tsx
import React, { memo, useCallback } from 'react';
import type { A2UIComponentProps } from '../core/types.js';

/**
 * TextField component — input with label, variant, and two-way value binding.
 */
export const TextField = memo(function TextField({
  props,
}: A2UIComponentProps) {
  const label = props.label?.value ?? '';
  const value = props.value?.value ?? '';
  const variant = props.variant?.value ?? 'shortText';

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
      props.value?.onUpdate(e.target.value);
    },
    [props.value],
  );

  const variantToType: Record<string, string> = {
    shortText: 'text',
    number: 'number',
    obscured: 'password',
  };

  return (
    <div className={`a2ui-text-field a2ui-text-field--${variant}`}>
      {label && <label className="a2ui-text-field__label">{label}</label>}
      {variant === 'longText' ? (
        <textarea
          className="a2ui-text-field__input"
          value={value}
          onChange={handleChange}
        />
      ) : (
        <input
          className="a2ui-text-field__input"
          type={variantToType[variant] ?? 'text'}
          value={value}
          onChange={handleChange}
        />
      )}
    </div>
  );
});

// renderers/lit/src/v0_9/standard_catalog/components/text-field.ts
import { html, TemplateResult } from 'lit';
import { TextFieldComponent } from '@a2ui/web_core/v0_9';

export const litTextField = new TextFieldComponent<TemplateResult>(
    ({ label, value, variant, onChange }) => {
        const type = variant === 'number' ? 'number' : 
                     variant === 'obscured' ? 'password' : 'text';
        return html`
            <div class="a2ui-text-field">
                <label>${label}</label>
                <input 
                    type="${type}" 
                    .value="${value}" 
                    @input="${(e: Event) => onChange((e.target as HTMLInputElement).value)}" 
                />
            </div>
        `;
    }
);
