// renderers/vue2/src/lib/rendering/renderer.vue
<!--
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<template>
  <component
    v-if="resolvedComponent"
    :is="resolvedComponent"
    :surface-id="surfaceId"
    :component="component"
    :weight="component.weight !== undefined ? component.weight : 'initial'"
    v-bind="additionalProps"
  />
</template>

<script lang="ts">
import Vue from 'vue';
import type { Component as VueComponent, PropType } from 'vue';
import type { Types } from '@a2ui/lit/0.8';
import { Styles } from '@a2ui/lit/0.8';
import { CATALOG_KEY, type Catalog, type CatalogEntry } from './catalog';

// Track whether structural styles have been injected
let hasInsertedStyles = false;

export default Vue.extend({
  name: 'A2UIRenderer',

  inject: {
    catalog: { from: CATALOG_KEY },
  },

  props: {
    surfaceId: {
      type: String as PropType<Types.SurfaceID>,
      required: true,
    },
    component: {
      type: Object as PropType<Types.AnyComponentNode>,
      required: true,
    },
  },

  data() {
    return {
      resolvedComponent: null as VueComponent | null,
      additionalProps: {} as Record<string, unknown>,
    };
  },

  watch: {
    component: {
      immediate: true,
      handler() {
        this.resolveComponent();
      },
    },
  },

  mounted() {
    // Inject structural styles once on first mount
    if (!hasInsertedStyles && typeof document !== 'undefined') {
      const styles = document.createElement('style');
      styles.textContent = Styles.structuralStyles;
      document.head.appendChild(styles);
      hasInsertedStyles = true;
    }
  },

  methods: {
    async resolveComponent() {
      const catalog = (this as any).catalog as Catalog;

      if (!catalog) {
        console.error('Catalog not provided. Make sure to use the A2UI plugin.');
        return;
      }

      const config = catalog[this.component.type];

      if (!config) {
        console.warn(`No component registered for type: ${this.component.type}`);
        this.resolvedComponent = null;
        this.additionalProps = {};
        return;
      }

      try {
        if (typeof config === 'function') {
          // Simple loader
          const result = await config();
          this.resolvedComponent = this.extractComponent(result);
          this.additionalProps = {};
        } else if (typeof config === 'object' && config.type) {
          // Loader with props mapping
          const result = await config.type();
          this.resolvedComponent = this.extractComponent(result);
          this.additionalProps = config.props(this.component);
        }
      } catch (error) {
        console.error(`Failed to load component for type: ${this.component.type}`, error);
        this.resolvedComponent = null;
        this.additionalProps = {};
      }
    },

    extractComponent(result: any): VueComponent {
      // Handle ES module default exports
      if (result && result.default) {
        return result.default;
      }
      return result;
    },
  },
});
</script>

// renderers/angular/src/v0_8/rendering/renderer.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  Directive,
  effect,
  inject,
  input,
  ViewContainerRef,
  Type,
  PLATFORM_ID,
} from '@angular/core';
import { DOCUMENT, isPlatformBrowser } from '@angular/common';
import { structuralStyles } from '@a2ui/web_core/styles/index';
import { Catalog } from './catalog';
import { Types } from '../types';

@Directive({
  selector: '[a2ui-renderer]',
  standalone: true,
})
export class Renderer {
  private static hasInsertedStyles = false;

  private readonly catalog = inject(Catalog);
  private readonly container = inject(ViewContainerRef);

  readonly surfaceId = input.required<Types.SurfaceID>();
  readonly component = input.required<Types.AnyComponentNode>();

  constructor() {
    const platformId = inject(PLATFORM_ID);
    const document = inject(DOCUMENT);

    if (!Renderer.hasInsertedStyles && isPlatformBrowser(platformId)) {
      const styleElement = document.createElement('style');
      styleElement.textContent = structuralStyles;
      document.head.appendChild(styleElement);
      Renderer.hasInsertedStyles = true;
    }

    effect(() => {
      const container = this.container;
      container.clear();

      const node = this.component();
      const config = this.catalog[node.type];

      if (!config) {
        console.error(`Unknown component type: ${node.type}`);
        return;
      }

      this.render(container, node, config);
    });
  }

  private async render(container: ViewContainerRef, node: Types.AnyComponentNode, config: any) {
    let componentType: Type<unknown> | null = null;

    if (typeof config === 'function') {
      const res = config();
      componentType = res instanceof Promise ? await res : res;
    } else if (typeof config === 'object' && config !== null) {
      if (typeof config.type === 'function') {
        const res = config.type();
        componentType = res instanceof Promise ? await res : res;
      } else {
        componentType = config.type;
      }
    }

    if (componentType) {
      const componentRef = container.createComponent(componentType);
      componentRef.setInput('surfaceId', this.surfaceId());
      componentRef.setInput('component', node);
      componentRef.setInput('weight', node.weight ?? 0);

      const props = node.properties as Record<string, unknown>;
      for (const [key, value] of Object.entries(props)) {
        try {
          componentRef.setInput(key, value);
        } catch (e) {
          console.warn(
            `[Renderer] Property "${key}" could not be set on component ${node.type}. If this property is required by the specification, ensure the component declares it as an input.`,
          );
        }
      }
    }
  }
}
