// renderers/react_prototype/src/adapter.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { useRef, useSyncExternalStore, useCallback } from "react";
import { z } from "zod";
import { ComponentContext, GenericBinder } from "@a2ui/web_core/v0_9";
import type { ComponentApi, ResolveA2uiProps } from "@a2ui/web_core/v0_9";

export interface ReactComponentImplementation extends ComponentApi {
  /** The framework-specific rendering wrapper. */
  render: React.FC<{
    context: ComponentContext;
    buildChild: (id: string, basePath?: string) => React.ReactNode;
  }>;
}

export type ReactA2uiComponentProps<T> = {
  props: T;
  buildChild: (id: string, basePath?: string) => React.ReactNode;
  context: ComponentContext;
};

// --- Component Factories ---

/**
 * Creates a React component implementation using the deep generic binder.
 */
export function createReactComponent<Schema extends z.ZodTypeAny>(
  api: { name: string; schema: Schema },
  RenderComponent: React.FC<ReactA2uiComponentProps<ResolveA2uiProps<z.infer<Schema>>>>
): ReactComponentImplementation {
  type Props = ResolveA2uiProps<z.infer<Schema>>;
  
  const ReactWrapper: React.FC<{ context: ComponentContext, buildChild: any }> = ({ context, buildChild }) => {
    const bindingRef = useRef<GenericBinder<Props>>(null);

    if (!bindingRef.current) {
      bindingRef.current = new GenericBinder<Props>(context, api.schema);
    }
    const binding = bindingRef.current;

    const subscribe = useCallback((callback: () => void) => {
      const sub = binding.subscribe(callback);
      return () => sub.unsubscribe();
    }, [binding]);

    const getSnapshot = useCallback(() => binding.snapshot, [binding]);
    const props = useSyncExternalStore(subscribe, getSnapshot);

    return <RenderComponent props={props || ({} as Props)} buildChild={buildChild} context={context} />;
  };

  return {
    name: api.name,
    schema: api.schema,
    render: ReactWrapper
  };
}

/**
 * Creates a React component implementation that manages its own context bindings (no generic binder).
 */
export function createBinderlessComponent(
  api: ComponentApi,
  RenderComponent: React.FC<{
    context: ComponentContext;
    buildChild: (id: string, basePath?: string) => React.ReactNode;
  }>
): ReactComponentImplementation {
  return {
    name: api.name,
    schema: api.schema,
    render: RenderComponent
  };
}

// renderers/lit/src/v0_9/adapter.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ReactiveController, LitElement } from "lit";
import { GenericBinder, ComponentContext, ComponentApi, ResolveA2uiProps, InferredComponentApiSchemaType } from "@a2ui/web_core/v0_9";

/**
 * A Lit ReactiveController that binds an A2UI component context to its API schema.
 * 
 * This controller manages the subscription to the GenericBinder, updating the 
 * component props and requesting a host update whenever the underlying layer data changes.
 * 
 * @template Api The specific A2UI component API interface this controller is bound to.
 */
export class A2uiController<Api extends ComponentApi> implements ReactiveController {
  /**
   * The current reactive properties of the A2UI component, matching the expected output schema.
   */
  public props: ResolveA2uiProps<InferredComponentApiSchemaType<Api>>;
  private binder: GenericBinder<InferredComponentApiSchemaType<Api>>;
  private subscription?: { unsubscribe: () => void };

  /**
   * Initializes the controller, binding it to the given Lit element and API schema.
   * 
   * @param host The LitElement acting as the component host. Must provide a component `context`.
   * @param api The A2UI component API defining the schema for this element.
   */
  constructor(private host: LitElement & { context: ComponentContext }, api: Api) {
    this.binder = new GenericBinder(this.host.context, api.schema);
    this.props = this.binder.snapshot as ResolveA2uiProps<InferredComponentApiSchemaType<Api>>;
    this.host.addController(this);
    if (this.host.isConnected) {
      this.hostConnected();
    }
  }

  /**
   * Subscribes to the GenericBinder updates when the host connects.
   * 
   * Triggers a request update on the host element when new props are received.
   */
  hostConnected() {
    if (!this.subscription) {
      this.subscription = this.binder.subscribe((newProps) => {
        this.props = newProps as ResolveA2uiProps<InferredComponentApiSchemaType<Api>>;
        this.host.requestUpdate();
      });
    }
  }

  /**
   * Unsubscribes from the GenericBinder updates when the host disconnects.
   */
  hostDisconnected() {
    this.subscription?.unsubscribe();
    this.subscription = undefined;
  }

  /**
   * Disposes the underlying GenericBinder to clean up resources from the context.
   */
  dispose() {
    this.binder.dispose();
  }
}
