// renderers/lit/src/0.8/ui/image.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { html, css, nothing } from "lit";
import { customElement, property } from "lit/decorators.js";
import { Root } from "./root.js";
import { Primitives, Types, A2uiMessageProcessor } from "@a2ui/web_core";
import { classMap } from "lit/directives/class-map.js";
import { styleMap } from "lit/directives/style-map.js";
import { structuralStyles } from "./styles.js";
import { Styles } from "../index.js";

@customElement("a2ui-image")
export class Image extends Root {
  @property()
  accessor url: Primitives.StringValue | null = null;

  @property()
  accessor usageHint: Types.ResolvedImage["usageHint"] | null = null;

  @property()
  accessor fit: "contain" | "cover" | "fill" | "none" | "scale-down" | null = null;

  static styles = [
    structuralStyles,
    css`
      * {
        box-sizing: border-box;
      }

      :host {
        display: block;
        flex: var(--weight);
        min-height: 0;
        overflow: auto;
      }

      img {
        display: block;
        width: 100%;
        height: 100%;
        object-fit: var(--object-fit, fill);
      }
    `,
  ];

  #renderImage() {
    if (!this.url) {
      return nothing;
    }

    const render = (url: string) => {
      return html`<img src=${url} />`;
    };

    if (this.url && typeof this.url === "object") {
      if ("literalString" in this.url) {
        const imageUrl = this.url.literalString ?? "";
        return render(imageUrl);
      } else if ("literal" in this.url) {
        const imageUrl = this.url.literal ?? "";
        return render(imageUrl);
      } else if (this.url && "path" in this.url && this.url.path) {
        if (!this.processor || !this.component) {
          return html`(no model)`;
        }

        const imageUrl = this.processor.getData(
          this.component,
          this.url.path,
          this.surfaceId ?? A2uiMessageProcessor.DEFAULT_SURFACE_ID
        );
        if (!imageUrl) {
          return html`Invalid image URL`;
        }

        if (typeof imageUrl !== "string") {
          return html`Invalid image URL`;
        }
        return render(imageUrl);
      }
    }

    return html`(empty)`;
  }

  render() {
    const classes = Styles.merge(
      this.theme.components.Image.all,
      this.usageHint ? this.theme.components.Image[this.usageHint] : {}
    );

    return html`<section
      class=${classMap(classes)}
      style=${styleMap({
        ...(this.theme.additionalStyles?.Image ?? {}),
        "--object-fit": this.fit ?? "fill",
      })}
    >
      ${this.#renderImage()}
    </section>`;
  }
}

// renderers/svelte/src/lib/catalog/Image.svelte
<!--
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<script lang="ts">
	import type { Types, Primitives } from '@a2ui/lit/0.8';
	import type { SvelteMessageProcessor } from '../data/processor.js';
	import { resolveString } from '../utils/primitives.js';
	import { classMap, styleMap } from '../utils/classes.js';

	interface Props {
		surfaceId: Types.SurfaceID | null;
		component: Types.ImageNode;
		weight: string | number;
		processor: SvelteMessageProcessor;
		theme: Types.Theme;
		url: Primitives.StringValue | null;
		usageHint?: Types.ResolvedImage['usageHint'] | null;
		fit?: 'contain' | 'cover' | 'fill' | 'none' | 'scale-down' | null;
	}

	let { surfaceId, component, weight, processor, theme, url, usageHint, fit }: Props = $props();

	let resolvedUrl = $derived(resolveString(processor, component, surfaceId, url) ?? '');
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	let imageClasses = $derived.by(() => {
		const allClasses = (theme.components.Image as any)?.all ?? {};
		const hintClasses = usageHint ? (theme.components.Image as any)?.[usageHint] ?? {} : {};
		return classMap({ ...allClasses, ...hintClasses });
	});
	let imageStyles = $derived(styleMap(theme.additionalStyles?.Image));
</script>

<div class="a2ui-image-host" style="--weight: {weight}; --object-fit: {fit ?? 'fill'}" data-usage-hint={usageHint}>
	<section class={imageClasses} style={imageStyles}>
		<img src={resolvedUrl} alt="" />
	</section>
</div>

<style>
	.a2ui-image-host {
		display: block;
		flex: var(--weight);
		min-height: 0;
		overflow: auto;
	}

	img {
		display: block;
		width: 100%;
		height: 100%;
		object-fit: var(--object-fit, fill);
	}
</style>
