// renderers/vue2/src/lib/catalog/row.vue
<!--
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<template>
  <div class="a2ui-row" :style="weightStyle">
    <section
      :class="classes"
      :style="theme.additionalStyles && theme.additionalStyles.Row"
    >
      <A2UIRenderer
        v-for="child in children"
        :key="child.id"
        :surface-id="surfaceId"
        :component="child"
      />
    </section>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import type { PropType } from 'vue';
import type { Types } from '@a2ui/lit/0.8';
import DynamicComponentMixin from '../rendering/mixins/dynamic-component';
import A2UIRenderer from '../rendering/renderer.vue';

export default Vue.extend({
  name: 'A2UIRow',

  mixins: [DynamicComponentMixin],

  components: {
    A2UIRenderer,
  },

  props: {
    alignment: {
      type: String as PropType<Types.ResolvedRow['alignment']>,
      default: 'stretch',
    },
    distribution: {
      type: String as PropType<Types.ResolvedRow['distribution']>,
      default: 'start',
    },
  },

  computed: {
    children(): Types.AnyComponentNode[] {
      return ((this as any).component as Types.RowNode).properties.children || [];
    },

    classes(): Record<string, boolean> {
      const theme = (this as any).theme as Types.Theme;
      return {
        ...theme.components.Row,
        [`align-${this.alignment}`]: true,
        [`distribute-${this.distribution}`]: true,
      };
    },
  },
});
</script>

<style>
.a2ui-row {
  display: flex;
  flex: var(--weight);
}

.a2ui-row > section {
  display: flex;
  flex-direction: row;
  width: 100%;
  min-height: 100%;
  box-sizing: border-box;
}

.a2ui-row .align-start {
  align-items: start;
}

.a2ui-row .align-center {
  align-items: center;
}

.a2ui-row .align-end {
  align-items: end;
}

.a2ui-row .align-stretch {
  align-items: stretch;
}

.a2ui-row .distribute-start {
  justify-content: start;
}

.a2ui-row .distribute-center {
  justify-content: center;
}

.a2ui-row .distribute-end {
  justify-content: end;
}

.a2ui-row .distribute-spaceBetween {
  justify-content: space-between;
}

.a2ui-row .distribute-spaceAround {
  justify-content: space-around;
}

.a2ui-row .distribute-spaceEvenly {
  justify-content: space-evenly;
}
</style>

// renderers/svelte/src/lib/catalog/Row.svelte
<!--
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<script lang="ts">
	import type { Types } from '@a2ui/lit/0.8';
	import type { SvelteMessageProcessor } from '../data/processor.js';
	import { classMap, styleMap } from '../utils/classes.js';
	import Renderer from '../rendering/Renderer.svelte';

	interface Props {
		surfaceId: Types.SurfaceID | null;
		component: Types.RowNode;
		weight: string | number;
		processor: SvelteMessageProcessor;
		theme: Types.Theme;
		alignment?: Types.ResolvedRow['alignment'];
		distribution?: Types.ResolvedRow['distribution'];
	}

	let {
		surfaceId,
		component,
		weight,
		processor,
		theme,
		alignment = 'stretch',
		distribution = 'start'
	}: Props = $props();

	let sectionClasses = $derived.by(() => {
		const classes = {
			...theme.components.Row,
			[`align-${alignment}`]: true,
			[`distribute-${distribution}`]: true
		};
		return classMap(classes);
	});

	let sectionStyles = $derived(styleMap(theme.additionalStyles?.Row));
</script>

<div
	class="a2ui-row-host"
	style="--weight: {weight}"
	data-alignment={alignment}
	data-distribution={distribution}
>
	<section class={sectionClasses} style={sectionStyles}>
		{#each component.properties.children as child (child.id)}
			<Renderer {surfaceId} component={child} />
		{/each}
	</section>
</div>

<style>
	.a2ui-row-host {
		display: flex;
		flex: var(--weight);
	}

	section {
		display: flex;
		flex-direction: row;
		width: 100%;
		min-height: 100%;
		box-sizing: border-box;
	}

	section :global(.align-start) {
		align-items: start;
	}

	section :global(.align-center) {
		align-items: center;
	}

	section :global(.align-end) {
		align-items: end;
	}

	section :global(.align-stretch) {
		align-items: stretch;
	}

	section :global(.distribute-start) {
		justify-content: start;
	}

	section :global(.distribute-center) {
		justify-content: center;
	}

	section :global(.distribute-end) {
		justify-content: end;
	}

	section :global(.distribute-spaceBetween) {
		justify-content: space-between;
	}

	section :global(.distribute-spaceAround) {
		justify-content: space-around;
	}

	section :global(.distribute-spaceEvenly) {
		justify-content: space-evenly;
	}
</style>
