// renderers/angular/src/lib/catalog/slider.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { Component, computed, input } from '@angular/core';
import { Primitives } from '@a2ui/web_core';
import { DynamicComponent } from '../rendering/dynamic-component';

@Component({
  selector: '[a2ui-slider]',
  template: `
    <section [class]="theme.components.Slider.container">
      <label [class]="theme.components.Slider.label" [for]="inputId">
        {{ label() }}
      </label>

      <input
        autocomplete="off"
        type="range"
        [value]="resolvedValue()"
        [min]="minValue()"
        [max]="maxValue()"
        [id]="inputId"
        (input)="handleInput($event)"
        [class]="theme.components.Slider.element"
        [style]="theme.additionalStyles?.Slider"
      />
    </section>
  `,
  styles: `
    :host {
      display: block;
      flex: var(--weight);
    }

    input {
      display: block;
      width: 100%;
      box-sizing: border-box;
    }
  `,
})
export class Slider extends DynamicComponent {
  readonly value = input.required<Primitives.NumberValue | null>();
  readonly label = input('');
  readonly minValue = input.required<number | undefined>();
  readonly maxValue = input.required<number | undefined>();

  protected readonly inputId = super.getUniqueId('a2ui-slider');
  protected resolvedValue = computed(() => super.resolvePrimitive(this.value()) ?? 0);

  protected handleInput(event: Event) {
    const path = this.value()?.path;

    if (!(event.target instanceof HTMLInputElement) || !path) {
      return;
    }

    this.processor.setData(this.component(), path, event.target.valueAsNumber, this.surfaceId());
  }
}

// renderers/svelte/src/lib/catalog/Slider.svelte
<!--
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<script lang="ts">
	import type { Types, Primitives } from '@a2ui/lit/0.8';
	import type { SvelteMessageProcessor } from '../data/processor.js';
	import { resolveNumber, generateId } from '../utils/primitives.js';
	import { classMap, styleMap } from '../utils/classes.js';

	interface Props {
		surfaceId: Types.SurfaceID | null;
		component: Types.SliderNode;
		weight: string | number;
		processor: SvelteMessageProcessor;
		theme: Types.Theme;
		value: Primitives.NumberValue | null;
		minValue: Primitives.NumberValue | null;
		maxValue: Primitives.NumberValue | null;
		label?: string;
	}

	let {
		surfaceId,
		component,
		weight,
		processor,
		theme,
		value,
		minValue,
		maxValue,
		label = ''
	}: Props = $props();

	const inputId = generateId('a2ui-slider');

	let currentValue = $derived(resolveNumber(processor, component, surfaceId, value) ?? 0);
	let min = $derived(resolveNumber(processor, component, surfaceId, minValue) ?? 0);
	let max = $derived(resolveNumber(processor, component, surfaceId, maxValue) ?? 100);

	let containerClasses = $derived(classMap(theme.components.Slider?.container));
	let inputClasses = $derived(classMap(theme.components.Slider?.element));
	let labelClasses = $derived(classMap(theme.components.Slider?.label));
	let containerStyles = $derived(styleMap(theme.additionalStyles?.Slider));

	function handleInput(event: Event) {
		const path = value?.path;

		if (!(event.target instanceof HTMLInputElement) || !path) {
			return;
		}

		processor.setData(component, path, parseFloat(event.target.value), surfaceId);
	}
</script>

<div class="a2ui-slider-host" style="--weight: {weight}">
	<section class={containerClasses} style={containerStyles}>
		<label for={inputId} class={labelClasses}>
			{label}
		</label>
		<input
			type="range"
			autocomplete="off"
			id={inputId}
			class={inputClasses}
			value={currentValue}
			min={min}
			max={max}
			oninput={handleInput}
		/>
		<span class={labelClasses}>{currentValue}</span>
	</section>
</div>

<style>
	.a2ui-slider-host {
		display: block;
		flex: var(--weight);
	}

	input {
		display: block;
		width: 100%;
	}
</style>
