// renderers/vue2/src/lib/catalog/text.vue
<!--
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<template>
  <section
    class="a2ui-text"
    :class="classes"
    :style="[weightStyle, additionalStyles]"
    v-html="resolvedText"
  ></section>
</template>

<script lang="ts">
import Vue from 'vue';
import type { PropType } from 'vue';
import type { Primitives, Types } from '@a2ui/lit/0.8';
import { Styles } from '@a2ui/lit/0.8';
import DynamicComponentMixin from '../rendering/mixins/dynamic-component';
import { markdownRenderer } from '../data/markdown';

interface HintedStyles {
  h1: Record<string, string>;
  h2: Record<string, string>;
  h3: Record<string, string>;
  h4: Record<string, string>;
  h5: Record<string, string>;
  body: Record<string, string>;
  caption: Record<string, string>;
}

export default Vue.extend({
  name: 'A2UIText',

  mixins: [DynamicComponentMixin],

  props: {
    text: {
      type: Object as PropType<Primitives.StringValue | null>,
      required: true,
    },
    usageHint: {
      type: String as PropType<Types.ResolvedText['usageHint'] | null>,
      default: null,
    },
  },

  computed: {
    resolvedText(): string {
      const usageHint = this.usageHint;
      let value = (this as any).resolvePrimitive(this.text);

      if (value == null) {
        return '(empty)';
      }

      switch (usageHint) {
        case 'h1':
          value = `# ${value}`;
          break;
        case 'h2':
          value = `## ${value}`;
          break;
        case 'h3':
          value = `### ${value}`;
          break;
        case 'h4':
          value = `#### ${value}`;
          break;
        case 'h5':
          value = `##### ${value}`;
          break;
        case 'caption':
          value = `*${value}*`;
          break;
        default:
          value = String(value);
          break;
      }

      const theme = (this as any).theme as Types.Theme;
      return markdownRenderer.render(
        value,
        Styles.appendToAll(theme.markdown, ['ol', 'ul', 'li'], {})
      );
    },

    classes(): Record<string, boolean> {
      const usageHint = this.usageHint;
      const theme = (this as any).theme as Types.Theme;

      return Styles.merge(
        theme.components.Text.all,
        usageHint ? theme.components.Text[usageHint as keyof typeof theme.components.Text] : {}
      );
    },

    additionalStyles(): Record<string, string> | null {
      const usageHint = this.usageHint;
      const theme = (this as any).theme as Types.Theme;
      const styles = theme.additionalStyles?.Text;

      if (!styles) {
        return null;
      }

      // Check if styles are hinted (have h1, h2, etc. keys)
      if (this.areHintedStyles(styles)) {
        return styles[usageHint ?? 'body'];
      }

      return styles as Record<string, string>;
    },
  },

  methods: {
    areHintedStyles(styles: unknown): styles is HintedStyles {
      if (typeof styles !== 'object' || !styles || Array.isArray(styles)) {
        return false;
      }

      const expected = ['h1', 'h2', 'h3', 'h4', 'h5', 'caption', 'body'];
      return expected.every((v) => v in styles);
    },
  },
});
</script>

<style>
.a2ui-text {
  display: block;
  flex: var(--weight);
}

.a2ui-text h1,
.a2ui-text h2,
.a2ui-text h3,
.a2ui-text h4,
.a2ui-text h5 {
  line-height: inherit;
  font: inherit;
}
</style>

// renderers/svelte/src/lib/catalog/Text.svelte
<!--
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<script lang="ts">
	import type { Types, Primitives } from '@a2ui/lit/0.8';
	import { Styles } from '@a2ui/lit/0.8';
	import type { SvelteMessageProcessor } from '../data/processor.js';
	import { resolveString } from '../utils/primitives.js';
	import { classMap, styleMap } from '../utils/classes.js';
	import { markdownRenderer } from '../data/markdown.js';

	interface Props {
		surfaceId: Types.SurfaceID | null;
		component: Types.TextNode;
		weight: string | number;
		processor: SvelteMessageProcessor;
		theme: Types.Theme;
		text: Primitives.StringValue | null;
		usageHint: Types.ResolvedText['usageHint'] | null;
	}

	let { surfaceId, component, weight, processor, theme, text, usageHint }: Props = $props();

	interface HintedStyles {
		h1: Record<string, string>;
		h2: Record<string, string>;
		h3: Record<string, string>;
		h4: Record<string, string>;
		h5: Record<string, string>;
		body: Record<string, string>;
		caption: Record<string, string>;
	}

	function isHintedStyles(styles: unknown): styles is HintedStyles {
		if (typeof styles !== 'object' || !styles || Array.isArray(styles)) {
			return false;
		}
		const expected = ['h1', 'h2', 'h3', 'h4', 'h5', 'caption', 'body'];
		return expected.every((v) => v in styles);
	}

	let resolvedText = $derived.by(() => {
		let value = resolveString(processor, component, surfaceId, text);

		if (value == null) {
			return '(empty)';
		}

		switch (usageHint) {
			case 'h1':
				value = `# ${value}`;
				break;
			case 'h2':
				value = `## ${value}`;
				break;
			case 'h3':
				value = `### ${value}`;
				break;
			case 'h4':
				value = `#### ${value}`;
				break;
			case 'h5':
				value = `##### ${value}`;
				break;
			case 'caption':
				value = `*${value}*`;
				break;
			default:
				value = String(value);
				break;
		}

		return markdownRenderer.render(
			value,
			Styles.appendToAll(theme.markdown, ['ol', 'ul', 'li'], {})
		);
	});

	type TextHint = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'caption' | 'body';

	let classes = $derived.by(() => {
		const hint = (usageHint ?? 'body') as TextHint;
		const merged = Styles.merge(
			theme.components.Text.all,
			theme.components.Text[hint] ?? {}
		);
		return classMap(merged);
	});

	let additionalStyles = $derived.by(() => {
		const styles = theme.additionalStyles?.Text;
		if (!styles) return '';

		const hint = (usageHint ?? 'body') as TextHint;
		let resolved: Record<string, string>;
		if (isHintedStyles(styles)) {
			resolved = styles[hint];
		} else {
			resolved = styles as Record<string, string>;
		}

		return styleMap(resolved);
	});
</script>

<section class={classes} style="--weight: {weight}; {additionalStyles}">
	{@html resolvedText}
</section>

<style>
	section {
		display: block;
		flex: var(--weight);
	}

	section :global(h1),
	section :global(h2),
	section :global(h3),
	section :global(h4),
	section :global(h5) {
		line-height: inherit;
		font: inherit;
	}
</style>
