// renderers/vue2/src/lib/catalog/multiple-choice.vue
<!--
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<template>
  <div class="a2ui-multiple-choice" :style="weightStyle">
    <section
      :class="theme.components.MultipleChoice.container"
      :style="theme.additionalStyles && theme.additionalStyles.MultipleChoice"
    >
      <label
        v-if="description"
        :for="inputId"
        :class="theme.components.MultipleChoice.label"
      >{{ description }}</label>

      <select
        :id="inputId"
        :class="theme.components.MultipleChoice.element"
        :value="currentSelection"
        @change="handleChange"
      >
        <option value="" disabled>Select an option</option>
        <option
          v-for="option in options"
          :key="option.value"
          :value="option.value"
        >{{ getOptionLabel(option) }}</option>
      </select>
    </section>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import type { PropType } from 'vue';
import type { Primitives, Types } from '@a2ui/lit/0.8';
import DynamicComponentMixin from '../rendering/mixins/dynamic-component';

interface SelectOption {
  label: Primitives.StringValue;
  value: string;
}

export default Vue.extend({
  name: 'A2UIMultipleChoice',

  mixins: [DynamicComponentMixin],

  props: {
    options: {
      type: Array as PropType<SelectOption[]>,
      default: () => [],
    },
    value: {
      type: Object as PropType<Types.ResolvedMultipleChoice['selections'] | null>,
      default: null,
    },
    description: {
      type: String,
      default: 'Select an item',
    },
  },

  data() {
    return {
      inputId: '',
    };
  },

  computed: {
    currentSelection(): string {
      if (!this.value) return '';

      // Handle path binding
      if (this.value.path) {
        const resolved = (this as any).processor.getData(
          (this as any).component,
          this.value.path,
          (this as any).surfaceId ?? undefined
        );
        if (Array.isArray(resolved)) {
          return resolved[0] ?? '';
        }
        return resolved ?? '';
      }

      // Handle literal array
      if (this.value.literalArray) {
        return this.value.literalArray[0] ?? '';
      }

      return '';
    },
  },

  created() {
    this.inputId = (this as any).getUniqueId('a2ui-select');
  },

  methods: {
    getOptionLabel(option: SelectOption): string | null {
      return (this as any).resolvePrimitive(option.label);
    },

    handleChange(event: Event) {
      const path = this.value?.path;
      const target = event.target as HTMLSelectElement;

      if (!target || !path) return;

      // Store as array for consistency
      (this as any).setData(path, [target.value]);
    },
  },
});
</script>

<style>
.a2ui-multiple-choice {
  display: flex;
  flex: var(--weight);
}

.a2ui-multiple-choice section,
.a2ui-multiple-choice select,
.a2ui-multiple-choice label {
  box-sizing: border-box;
}

.a2ui-multiple-choice select {
  display: block;
  width: 100%;
}

.a2ui-multiple-choice label {
  display: block;
  margin-bottom: 4px;
}
</style>

// renderers/angular/src/lib/catalog/multiple-choice.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { Component, computed, input } from '@angular/core';
import { DynamicComponent } from '../rendering/dynamic-component';
import { Primitives, Types } from '@a2ui/lit/0.8';

@Component({
  selector: 'a2ui-multiple-choice',
  template: `
    <section [class]="theme.components.MultipleChoice.container">
      <label [class]="theme.components.MultipleChoice.label" [for]="selectId">{{
        description()
      }}</label>

      <select
        (change)="handleChange($event)"
        [id]="selectId"
        [multiple]="isMultiple()"
        [class]="theme.components.MultipleChoice.element"
        [style]="theme.additionalStyles?.MultipleChoice"
      >
        @for (option of options(); track option.value) {
          <option
            [value]="option.value"
            [selected]="selectedValues().includes(option.value)"
          >
            {{ resolvePrimitive(option.label) }}
          </option>
        }
      </select>
    </section>
  `,
  styles: `
    :host {
      display: block;
      flex: var(--weight);
      min-height: 0;
      overflow: auto;
    }

    select {
      width: 100%;
      box-sizing: border-box;
    }
  `,
})
export class MultipleChoice extends DynamicComponent {
  readonly options = input.required<{ label: Primitives.StringValue; value: string }[]>();
  readonly selections =
    input.required<Types.ResolvedMultipleChoice['selections'] | Primitives.StringValue | null>();
  readonly maxAllowedSelections = input<number | null>(null);
  readonly description = input.required<string>();

  protected readonly selectId = super.getUniqueId('a2ui-multiple-choice');
  protected selectedValues = computed(() => this.resolveSelections());
  protected isMultiple = computed(() => {
    const maxSelections = this.maxAllowedSelections();
    const selections = this.selectedValues();
    return typeof maxSelections === 'number' ? maxSelections > 1 : selections.length > 1;
  });

  protected handleChange(event: Event) {
    const selections = this.selections();
    const path = selections?.path;

    if (!(event.target instanceof HTMLSelectElement) || !path) {
      return;
    }

    const isMultiple = this.isMultiple();
    const selectedValues = isMultiple
      ? Array.from(event.target.selectedOptions).map((option) => option.value)
      : [event.target.value];
    const maxSelections = this.maxAllowedSelections();
    const nextSelections =
      typeof maxSelections === 'number' && selectedValues.length > maxSelections
        ? selectedValues.slice(0, maxSelections)
        : selectedValues;

    if (isMultiple && nextSelections.length !== selectedValues.length) {
      const allowed = new Set(nextSelections);
      for (const option of Array.from(event.target.options)) {
        option.selected = allowed.has(option.value);
      }
    }

    this.processor.setData(this.component(), path, nextSelections, this.surfaceId());
  }

  private resolveSelections() {
    const selections = this.selections();

    if (!selections || typeof selections !== 'object') {
      return [];
    }

    if ('literalArray' in selections) {
      return Array.isArray(selections.literalArray) ? selections.literalArray : [];
    }

    if ('literalString' in selections) {
      return selections.literalString ? [selections.literalString] : [];
    }

    if ('literal' in selections) {
      return selections.literal != null ? [selections.literal] : [];
    }

    if (selections.path) {
      const resolved = this.processor.getData(
        this.component(),
        selections.path,
        this.surfaceId() ?? undefined,
      );
      if (Array.isArray(resolved)) {
        return resolved.filter((value): value is string => typeof value === 'string');
      }
      return typeof resolved === 'string' ? [resolved] : [];
    }

    return [];
  }
}
