// angular/projects/rizzcharts/src/components/chat/chat.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import { ChatHistory } from '@rizzcharts/components/chat/chat-history/chat-history';
import { InputArea } from '@rizzcharts/components/chat/input-area/input-area';
import { ChatService } from '@rizzcharts/services/chat_service';

@Component({
  selector: 'chat',
  imports: [ChatHistory, InputArea],
  templateUrl: './chat.html',
  styleUrl: './chat.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Chat {
  private chatService = inject(ChatService);

  readonly history = computed(() => this.chatService.history());
}

// samples/client/react/projects/a2a-chat-canvas/src/components/Chat.tsx
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import React from "react";
import { ChatHistory } from "./ChatHistory";
import { InputArea } from "./InputArea";
import { MessageDecoratorProps } from "../types";

interface ChatProps {
  emptyHistoryContent?: React.ReactNode;
  messageDecorator?: React.ComponentType<MessageDecoratorProps>;
  className?: string;
}

/**
 * Chat component that combines the chat history and input area.
 */
export function Chat({
  emptyHistoryContent,
  messageDecorator,
  className,
}: ChatProps) {
  return (
    <div className={`chat ${className || ""}`}>
      <ChatHistory
        emptyContent={emptyHistoryContent}
        messageDecorator={messageDecorator}
        className="chat-history-container"
      />
      <InputArea className="chat-input-container" />
    </div>
  );
}
