// angular/projects/rizzcharts/src/components/chat/message/message.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';
import { AgentHeader } from '@rizzcharts/components/chat/agent-header/agent-header';
import { MessageActions } from '@rizzcharts/components/chat/message-actions/message-actions';
import { MessageContent } from '@rizzcharts/components/chat/message/message-content/message-content';
import { ChatService } from '@rizzcharts/services/chat_service';
import { Role, UiAgent, UiMessage } from '@rizzcharts/types/ui_message';

@Component({
  selector: 'message',
  imports: [AgentHeader, MessageActions, MessageContent],
  templateUrl: './message.html',
  styleUrl: './message.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Message {
  readonly uiMessage = input.required<UiMessage>();

  protected readonly showProgressIndicator = computed(() => {
    return this.uiMessage().status === 'pending';
  });
  protected readonly surfaces = computed(() => this.chatService.surfaces());

  private readonly chatService = inject(ChatService);

  isRoleAgent(role: Role): role is UiAgent {
    return role.type === 'ui_agent';
  }
}

// samples/client/react/projects/a2a-chat-canvas/src/components/Message.tsx
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { A2UIRenderer } from "@a2ui/react";
import { UiMessage, UiAgent, MessageDecoratorProps } from "../types";
import { formatTimestamp } from "../utils";
import { useChatContext } from "../context/ChatContext";

interface MessageProps {
  message: UiMessage;
  decorator?: React.ComponentType<MessageDecoratorProps>;
}

/**
 * Message component that displays a single chat message.
 */
export function Message({ message, decorator: Decorator }: MessageProps) {
  const { a2uiSurfaces } = useChatContext();
  const isUser = message.role.type === "ui_user";
  const isAgent = message.role.type === "ui_agent";
  const agentRole = isAgent ? (message.role as UiAgent) : null;

  const content = (
    <div className={`message ${isUser ? "user-message" : "agent-message"}`}>
      <div className="message-avatar">
        {isAgent && agentRole?.iconUrl ? (
          <img src={agentRole.iconUrl} alt={agentRole.name} />
        ) : isAgent ? (
          <div className="agent-avatar">{agentRole?.name?.charAt(0) || "A"}</div>
        ) : (
          <div className="user-avatar">U</div>
        )}
      </div>

      <div className="message-content">
        <div className="message-header">
          <span className="message-sender">
            {isAgent ? agentRole?.name : "You"}
            {agentRole?.subagentName && (
              <span className="subagent-name"> via {agentRole.subagentName}</span>
            )}
          </span>
          <span className="message-time">{formatTimestamp(message.created)}</span>
        </div>

        <div className="message-body">
          {message.status === "pending" && message.contents.length === 0 ? (
            <div className="loading-indicator">
              <span className="dot" />
              <span className="dot" />
              <span className="dot" />
            </div>
          ) : (
            message.contents.map((content) => (
              <MessageContent
                key={content.id}
                content={content}
                surfaceIds={Array.from(a2uiSurfaces.keys())}
              />
            ))
          )}
        </div>
      </div>
    </div>
  );

  if (Decorator) {
    return <Decorator message={message}>{content}</Decorator>;
  }

  return content;
}

interface MessageContentProps {
  content: UiMessage["contents"][0];
  surfaceIds: string[];
}

function MessageContent({ content, surfaceIds }: MessageContentProps) {
  if (content.data.kind === "text") {
    return <p className="text-content">{content.data.text}</p>;
  }

  if (content.variant === "a2ui_data_part") {
    return (
      <div className="a2ui-content">
        {surfaceIds.map((surfaceId) => (
          <A2UIRenderer
            key={surfaceId}
            surfaceId={surfaceId}
            className="embedded-surface"
          />
        ))}
      </div>
    );
  }

  return <pre className="json-content">{JSON.stringify(content.data, null, 2)}</pre>;
}
