// renderers/lit/src/v0_9/surface/A2uiSurface.ts
import { html, nothing, LitElement, PropertyValues } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { SurfaceModel, ComponentContext } from "@a2ui/web_core/v0_9";
import "./render-node.js";

@customElement("a2ui-surface")
export class A2uiSurface extends LitElement {
  @property({ type: Object }) accessor surface: SurfaceModel<any> | undefined = undefined;
  
  @state() accessor _hasRoot = false;
  private unsub?: () => void;

  createRenderRoot() {
    return this;
  }

  protected willUpdate(changedProperties: PropertyValues) {
    if (changedProperties.has('surface')) {
      if (this.unsub) {
        this.unsub();
        this.unsub = undefined;
      }
      this._hasRoot = !!this.surface?.componentsModel.get("root");
      
      if (this.surface && !this._hasRoot) {
        const sub = this.surface.componentsModel.onCreated.subscribe((comp) => {
          if (comp.id === "root") {
            this._hasRoot = true;
            this.unsub?.();
            this.unsub = undefined;
          }
        });
        this.unsub = () => sub.unsubscribe();
      }
    }
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    if (this.unsub) {
      this.unsub();
      this.unsub = undefined;
    }
  }

  render() {
    if (!this.surface) return nothing;
    if (!this._hasRoot) {
      return html`<slot name="loading"><div>Loading surface...</div></slot>`;
    }
    
    try {
        const rootContext = new ComponentContext(this.surface, "root", "/");
        return html`<a2ui-node .context=${rootContext}></a2ui-node>`;
    } catch (e) {
        console.error("Error creating root context:", e);
        return html`<div>Error rendering surface</div>`;
    }
  }
}

// renderers/react_prototype/src/A2uiSurface.tsx
import React, { useSyncExternalStore } from 'react';
import { SurfaceModel, ComponentContext } from '@a2ui/web_core/v0_9';
import type { ReactComponentImplementation } from './adapter';

export const A2uiSurface: React.FC<{ surface: SurfaceModel<ReactComponentImplementation> }> = ({ surface }) => {
  const store = React.useMemo(() => {
    let version = 0;
    return {
      subscribe: (cb: () => void) => {
        const unsub1 = surface.componentsModel.onCreated.subscribe(() => { version++; cb(); });
        const unsub2 = surface.componentsModel.onDeleted.subscribe(() => { version++; cb(); });
        return () => { unsub1.unsubscribe(); unsub2.unsubscribe(); };
      },
      getSnapshot: () => version
    };
  }, [surface]);

  useSyncExternalStore(store.subscribe, store.getSnapshot);

  const renderComponent = (id: string, currentBasePath: string) => {
    try {
      const componentModel = surface.componentsModel.get(id);
      if (!componentModel) {
        return <div key={`loading-${id}`} style={{ color: 'gray', padding: '4px' }}>[Loading {id}...]</div>;
      }
      
      const compImpl = surface.catalog.components.get(componentModel.type);
      
      if (!compImpl) {
        return <div key={`error-${id}`} style={{ color: 'red' }}>Unknown component: {componentModel.type}</div>;
      }
      
      const ComponentToRender = compImpl.render;
      const context = new ComponentContext(surface, id, currentBasePath);
      
      const buildChild = (childId: string, specificPath?: string) => {
        return renderComponent(childId, specificPath || context.dataContext.path);
      };

      return <ComponentToRender key={`${id}-${currentBasePath}`} context={context} buildChild={buildChild} />;
    } catch (e: any) {
      return <div key={`error-${id}`} style={{ color: 'red' }}>Error rendering {id}: {e.message}</div>;
    }
  };

  const hasRoot = surface.componentsModel.get('root') !== undefined;

  if (!hasRoot) {
    return <div>Waiting for root component...</div>;
  }

  return <>{renderComponent("root", "/")}</>;
};
