// samples/client/angular/projects/orchestrator/src/a2ui-catalog/chart.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { DynamicComponent } from '@a2ui/angular';
import { Types, Primitives } from '@a2ui/web_core';
import { Component, computed, input, Signal, signal, ViewChild } from '@angular/core';
import { MatIconButton } from '@angular/material/button';
import { MatIcon } from '@angular/material/icon';
import {
  ChartData,
  ChartEvent,
  Chart as ChartJS,
  ChartOptions,
  ChartType,
  LegendItem,
} from 'chart.js';
import ChartDataLabels from 'chartjs-plugin-datalabels';
import { BaseChartDirective } from 'ng2-charts';

ChartJS.register(ChartDataLabels);

@Component({
  selector: 'a2ui-chart',
  imports: [BaseChartDirective, MatIconButton, MatIcon],
  styles: `
    :host {
      display: block;
      flex: var(--weight);
      padding: 20px;
    }

    .chart-box-container {
      background-color: var(--mat-sys-surface-container); /* Dark background for the box */
      border-radius: 8px;
      border: 1px solid #444; /* Subtle border for dark theme */
      padding: 20px;
      margin: 20px auto; /* Center the box */
      max-width: 800px; /* Limit width for better appearance */
    }

    /* Combined header for title and icon */
    .chart-header {
      display: flex;
      justify-content: space-between; /* Pushes title to left, icon to right */
      align-items: start; /* Vertically centers title and icon */
      margin-bottom: 15px; /* Space below the header */
    }

    .chart-header h2 {
      margin: 0; /* Remove default margin from h2 */
      font-size: 24px;
      color: var(--mat-sys-on-surface-container); /* Light text for title */
    }

    .header-icon {
      cursor: pointer;
      line-height: 0; /* Helps with vertical alignment of SVG */
    }

    .chart-container {
      width: 100%;
      display: flex;
      flex-direction: column;
      font-family: Arial, sans-serif;
      color: #ccc; /* Light text for dark theme */
    }

    .chart-container p {
      margin-bottom: 10px;
      color: #ccc; /* Light text for dark theme */
    }
  `,
  template: `
    <div class="chart-box-container">
      <!-- Combined header for title and icon -->
      <div class="chart-header">
        <div>
          <h2>{{ resolvedTitle() }}</h2>
          @if (isDrillDown()) {
            <h3>{{ selectedCategory() }}</h3>
          }
        </div>

        <div>
          <button matIconButton>
            <mat-icon>download</mat-icon>
          </button>
          <button matIconButton>
            <mat-icon>share</mat-icon>
          </button>
        </div>
      </div>
      <div class="chart-container">
        @if (isDrillDown()) {
          <button matIconButton (click)="restoreOriginalView()">
            <mat-icon>arrow_back</mat-icon>
          </button>
        }

        <canvas
          baseChart
          [data]="currentData()"
          [type]="chartType()"
          [options]="chartOptions"
          (chartClick)="onClick($event)"
        ></canvas>
      </div>
    </div>
  `,
})
export class Chart extends DynamicComponent<Types.CustomNode> {
  readonly type = input.required<string>();
  protected readonly chartType = computed(() => this.type() as ChartType);

  readonly title = input<Primitives.StringValue | null>();
  protected readonly resolvedTitle: Signal<string | null> = computed(() =>
    super.resolvePrimitive(this.title() ?? null),
  );

  readonly chartData = input.required<Primitives.StringValue | null>();
  protected readonly resolvedPieChartData: Signal<
    Map<string, ChartData<'pie', number[], string>> | undefined
  > = computed(() => {
    const chartDataPathPrefix = this.chartData();
    const chartType = this.chartType();
    if (chartDataPathPrefix === null) {
      return undefined;
    }
    if (chartType === 'pie' || chartType === 'doughnut') {
      return this.resolvePieChartData(chartDataPathPrefix);
    }
    console.error('Unsupported chart type specified:', chartType);
    return undefined;
  });

  protected readonly selectedCategory = signal('root');
  protected readonly isDrillDown = computed(() => this.selectedCategory() !== 'root');
  protected readonly currentData: Signal<ChartData<'pie', number[], string> | undefined> = computed(
    () => {
      const selectedCategory: string = this.selectedCategory();
      const allData = this.resolvedPieChartData();
      if (!allData) {
        return undefined;
      }
      return { ...allData.get(selectedCategory) } as ChartData<'pie', number[], string>;
    },
  );

  @ViewChild(BaseChartDirective) chart?: BaseChartDirective;
  protected chartOptions: ChartOptions = {
    responsive: true,
    plugins: {
      legend: {
        display: true,
        position: 'right',
        labels: {
          color: '#166a8f',
          font: {
            size: 14,
          },
        },
        onClick: (e: ChartEvent, legendItem: LegendItem) => {
          this.updateChartWithCategory(legendItem.text);
        },
      },
      datalabels: {
        formatter: (value: number, ctx: any) => {
          const total = (ctx.chart.data.datasets[0].data as number[]).reduce((a, b) => a + b, 0);
          const percentage = Math.round((value / total) * 100);
          return `${percentage.toFixed(1)}%`;
        },
        color: 'white',
        font: {
          size: 16,
        },
      },
    },
  };

  private resolvePieChartData(
    pathPrefix: Primitives.StringValue,
  ): Map<string, ChartData<'pie', number[], string>> | undefined {
    const dataMap = new Map<string, ChartData<'pie', number[], string>>();
    const labels: string[] = [];
    const data: number[] = [];
    if (pathPrefix?.path) {
      for (let index: number = 0; index < 500; index++) {
        const itemPrefix = `${pathPrefix.path}[${index}]`;
        const labelPath: Primitives.StringValue = { path: `${itemPrefix}.label` };
        const valuePath: Primitives.NumberValue = { path: `${itemPrefix}.value` };
        const label = super.resolvePrimitive(labelPath);
        const value = super.resolvePrimitive(valuePath);
        if (label === null || value === null) {
          break;
        }
        labels.push(label);
        data.push(value);

        const drilldownLabels: string[] = [];
        const drilldownData: number[] = [];
        const drilldownPathPrefix = `${itemPrefix}.drillDown`;
        for (let jindex: number = 0; jindex < 500; jindex++) {
          const drilldownItemPrefix = `${drilldownPathPrefix}[${jindex}]`;
          const drilldownLabelPath: Primitives.StringValue = {
            path: `${drilldownItemPrefix}.label`,
          };
          const drilldownValuePath: Primitives.NumberValue = {
            path: `${drilldownItemPrefix}.value`,
          };
          const drilldownLabel = super.resolvePrimitive(drilldownLabelPath);
          const drilldownValue = super.resolvePrimitive(drilldownValuePath);
          if (drilldownLabel === null || drilldownValue === null) {
            break;
          }
          drilldownLabels.push(drilldownLabel);
          drilldownData.push(drilldownValue);
        }

        const drilldownChartData: ChartData<'pie', number[], string> = {
          labels: drilldownLabels,
          datasets: [
            {
              data: drilldownData,
            },
          ],
        };
        dataMap.set(label, drilldownChartData);
      }
    }

    const rootData: ChartData<'pie', number[], string> = {
      labels,
      datasets: [
        {
          data,
        },
      ],
    };
    dataMap.set('root', rootData);
    return dataMap;
  }

  public restoreOriginalView() {
    this.selectedCategory.set('root');
  }

  protected onClick(e: { event?: ChartEvent; active?: any[] | undefined }) {
    const active = e.active;
    if (!active || active.length === 0) return;

    // active[0] for pie chart contains the data index that was clicked
    // @ts-ignore -- ActiveElement typing can vary between versions
    const dataIndex: number | undefined = (active[0] as any).index;
    const labels = [...(this.currentData()?.labels ?? [])];
    const label = labels && typeof dataIndex === 'number' ? labels[dataIndex] : undefined;
    if (label) {
      this.updateChartWithCategory(label);
    }
  }

  private updateChartWithCategory(label: string) {
    const currentCategory = this.selectedCategory();
    if (currentCategory !== 'root') {
      console.error('Cannot drilldown further');
      return;
    }
    this.selectedCategory.set(label);
  }
}

// samples/client/react/projects/rizzcharts/src/components/Chart.tsx
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { useState, useMemo, useCallback } from "react";
import { Types, Primitives, useDataBinding } from "@a2ui/react";
import {
  Chart as ChartJS,
  ArcElement,
  Tooltip,
  Legend,
  ChartData,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
} from "chart.js";
import ChartDataLabels from "chartjs-plugin-datalabels";
import { Pie, Doughnut, Bar } from "react-chartjs-2";
import "./Chart.css";

ChartJS.register(
  ArcElement,
  Tooltip,
  Legend,
  ChartDataLabels,
  CategoryScale,
  LinearScale,
  BarElement,
  Title
);

// Chart.js default color palette
const CHART_COLORS = [
  "rgba(255, 99, 132, 0.8)",   // Red
  "rgba(54, 162, 235, 0.8)",   // Blue
  "rgba(255, 206, 86, 0.8)",   // Yellow
  "rgba(75, 192, 192, 0.8)",   // Teal
  "rgba(153, 102, 255, 0.8)",  // Purple
  "rgba(255, 159, 64, 0.8)",   // Orange
  "rgba(199, 199, 199, 0.8)",  // Grey
  "rgba(83, 102, 255, 0.8)",   // Indigo
  "rgba(255, 99, 255, 0.8)",   // Pink
  "rgba(99, 255, 132, 0.8)",   // Green
];

const CHART_BORDER_COLORS = [
  "rgba(255, 99, 132, 1)",
  "rgba(54, 162, 235, 1)",
  "rgba(255, 206, 86, 1)",
  "rgba(75, 192, 192, 1)",
  "rgba(153, 102, 255, 1)",
  "rgba(255, 159, 64, 1)",
  "rgba(199, 199, 199, 1)",
  "rgba(83, 102, 255, 1)",
  "rgba(255, 99, 255, 1)",
  "rgba(99, 255, 132, 1)",
];

interface ChartProperties {
  type?: Primitives.StringValue;
  title?: Primitives.StringValue;
  chartData?: Primitives.StringValue;
}

interface ChartProps {
  node: Types.AnyComponentNode & { properties: ChartProperties };
  surfaceId: string;
}

export function Chart({ node, surfaceId }: ChartProps) {
  const { resolveString, getValue } = useDataBinding(node, surfaceId);
  const [selectedCategory, setSelectedCategory] = useState<string>("root");

  const properties = node.properties;
  const chartType = resolveString(properties.type ?? null) ?? "pie";
  const title = resolveString(properties.title ?? null);
  const chartDataPath = properties.chartData?.path;

  const chartDataMap = useMemo(() => {
    if (!chartDataPath) return null;

    const dataMap = new Map<string, ChartData<"pie" | "bar", number[], string>>();
    const labels: string[] = [];
    const values: number[] = [];

    for (let index = 0; index < 500; index++) {
      const itemPrefix = `${chartDataPath}[${index}]`;
      const label = getValue(`${itemPrefix}.label`);
      const value = getValue(`${itemPrefix}.value`);

      if (label === null || value === null) break;

      labels.push(String(label));
      values.push(Number(value));

      const drilldownLabels: string[] = [];
      const drilldownValues: number[] = [];
      const drilldownPathPrefix = `${itemPrefix}.drillDown`;

      for (let jIndex = 0; jIndex < 500; jIndex++) {
        const drilldownItemPrefix = `${drilldownPathPrefix}[${jIndex}]`;
        const drilldownLabel = getValue(`${drilldownItemPrefix}.label`);
        const drilldownValue = getValue(`${drilldownItemPrefix}.value`);

        if (drilldownLabel === null || drilldownValue === null) break;

        drilldownLabels.push(String(drilldownLabel));
        drilldownValues.push(Number(drilldownValue));
      }

      if (drilldownLabels.length > 0) {
        dataMap.set(String(label), {
          labels: drilldownLabels,
          datasets: [{
            data: drilldownValues,
            backgroundColor: CHART_COLORS.slice(0, drilldownValues.length),
            borderColor: CHART_BORDER_COLORS.slice(0, drilldownValues.length),
            borderWidth: 2,
          }],
        });
      }
    }

    dataMap.set("root", {
      labels,
      datasets: [{
        data: values,
        backgroundColor: CHART_COLORS.slice(0, values.length),
        borderColor: CHART_BORDER_COLORS.slice(0, values.length),
        borderWidth: 2,
      }],
    });

    return dataMap;
  }, [chartDataPath, getValue]);

  const currentData = useMemo(() => {
    if (!chartDataMap) return null;
    return chartDataMap.get(selectedCategory) ?? null;
  }, [chartDataMap, selectedCategory]);

  const isDrillDown = selectedCategory !== "root";

  const handleChartClick = useCallback(
    (_: unknown, elements: Array<{ index: number }>) => {
      if (!elements.length || isDrillDown) return;

      const clickedIndex = elements[0].index;
      const clickedLabel = currentData?.labels?.[clickedIndex];

      if (clickedLabel && chartDataMap?.has(String(clickedLabel))) {
        setSelectedCategory(String(clickedLabel));
      }
    },
    [currentData, chartDataMap, isDrillDown]
  );

  const handleRestoreOriginal = useCallback(() => {
    setSelectedCategory("root");
  }, []);

  const isPieOrDoughnut = chartType === "pie" || chartType === "doughnut";

  const chartOptions = useMemo(
    () => ({
      responsive: true,
      maintainAspectRatio: true,
      plugins: {
        legend: {
          display: true,
          position: isPieOrDoughnut ? "right" as const : "top" as const,
          labels: {
            color: "#94a3b8",
            font: { size: 14 },
          },
          onClick: isPieOrDoughnut
            ? (_: unknown, legendItem: { text: string }) => {
                if (!isDrillDown && chartDataMap?.has(legendItem.text)) {
                  setSelectedCategory(legendItem.text);
                }
              }
            : undefined,
        },
        datalabels: isPieOrDoughnut
          ? {
              formatter: (value: number, ctx: any) => {
                const dataset = ctx.chart.data.datasets[0];
                const total = dataset.data.reduce((a: number, b: number) => a + b, 0);
                const percentage = ((value / total) * 100).toFixed(1);
                return `${percentage}%`;
              },
              color: "white",
              font: { size: 14, weight: "bold" as const },
            }
          : {
              display: false,
            },
      },
      scales: isPieOrDoughnut
        ? undefined
        : {
            x: {
              grid: { color: "rgba(255, 255, 255, 0.1)" },
              ticks: { color: "#94a3b8" },
            },
            y: {
              grid: { color: "rgba(255, 255, 255, 0.1)" },
              ticks: { color: "#94a3b8" },
              beginAtZero: true,
            },
          },
      onClick: isPieOrDoughnut ? handleChartClick : undefined,
    }),
    [handleChartClick, isDrillDown, chartDataMap, isPieOrDoughnut]
  );

  if (!currentData) {
    return (
      <div className="chart-box-container">
        <div className="chart-header">
          <h2>{title ?? "Chart"}</h2>
        </div>
        <div className="chart-container">
          <p>No chart data available</p>
        </div>
      </div>
    );
  }

  return (
    <div className="chart-box-container">
      <div className="chart-header">
        <div>
          <h2>{title ?? "Chart"}</h2>
          {isDrillDown && <h3>{selectedCategory}</h3>}
        </div>
        <div className="chart-actions">
          <button className="icon-button" title="Download">
            <DownloadIcon />
          </button>
          <button className="icon-button" title="Share">
            <ShareIcon />
          </button>
        </div>
      </div>
      <div className="chart-container">
        {isDrillDown && (
          <button className="back-button" onClick={handleRestoreOriginal}>
            <BackIcon />
          </button>
        )}
        {chartType === "bar" ? (
          <Bar data={currentData as any} options={chartOptions as any} />
        ) : chartType === "doughnut" ? (
          <Doughnut data={currentData as any} options={chartOptions as any} />
        ) : (
          <Pie data={currentData as any} options={chartOptions as any} />
        )}
      </div>
    </div>
  );
}

function DownloadIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
      <path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z" />
    </svg>
  );
}

function ShareIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
      <path d="M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92s2.92-1.31 2.92-2.92-1.31-2.92-2.92-2.92z" />
    </svg>
  );
}

function BackIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
      <path d="M20 11H7.83l5.59-5.59L12 4l-8 8 8 8 1.41-1.41L7.83 13H20v-2z" />
    </svg>
  );
}
