// renderers/react/src/v0_9/catalog/basic/utils.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type React from 'react';

/** Standard leaf margin from the implementation guide. */
export const LEAF_MARGIN = '8px';

/** Standard internal padding for visually bounded containers. */
export const CONTAINER_PADDING = '16px';

/** Standard border for cards and inputs. */
export const STANDARD_BORDER = '1px solid #ccc';

/** Standard border radius. */
export const STANDARD_RADIUS = '8px';

export {mapJustify, mapAlign} from '@a2ui/web_core/v0_9';

export const getBaseLeafStyle = (): React.CSSProperties => ({
  margin: LEAF_MARGIN,
  boxSizing: 'border-box',
});

export const getBaseContainerStyle = (): React.CSSProperties => ({
  margin: LEAF_MARGIN,
  padding: CONTAINER_PADDING,
  border: STANDARD_BORDER,
  borderRadius: STANDARD_RADIUS,
  boxSizing: 'border-box',
});

// renderers/angular/src/lib/v0_9/core/utils.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { DestroyRef, Signal, signal as angularSignal } from '@angular/core';
import { Signal as PreactSignal, effect } from '@a2ui/web_core/v0_9';

/**
 * Bridges a Preact Signal to an Angular Signal.
 * Automatically cleans up the Preact effect and any signal-specific resources on destroy.
 *
 * @param preactSignal The source Preact Signal.
 * @param destroyRef Angular DestroyRef for lifecycle management.
 * @returns A read-only Angular Signal.
 */
import { NgZone } from '@angular/core';

export function toAngularSignal<T>(
  preactSignal: PreactSignal<T>,
  destroyRef: DestroyRef,
  ngZone?: NgZone,
): Signal<T> {
  const s = angularSignal(preactSignal.peek());
  
  const dispose = effect(() => {
    if (ngZone) {
      ngZone.run(() => s.set(preactSignal.value));
    } else {
      s.set(preactSignal.value);
    }
  });

  destroyRef.onDestroy(() => {
    dispose();
    // Some signals returned by DataContext.resolveSignal have a custom unsubscribe for AbortControllers
    if ((preactSignal as any).unsubscribe) {
      (preactSignal as any).unsubscribe();
    }
  });

  return s.asReadonly();
}
