// renderers/svelte/src/lib/catalog/Slider.svelte
<!--
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<script lang="ts">
	import type { Types, Primitives } from '@a2ui/lit/0.8';
	import type { SvelteMessageProcessor } from '../data/processor.js';
	import { resolveNumber, generateId } from '../utils/primitives.js';
	import { classMap, styleMap } from '../utils/classes.js';

	interface Props {
		surfaceId: Types.SurfaceID | null;
		component: Types.SliderNode;
		weight: string | number;
		processor: SvelteMessageProcessor;
		theme: Types.Theme;
		value: Primitives.NumberValue | null;
		minValue: Primitives.NumberValue | null;
		maxValue: Primitives.NumberValue | null;
		label?: string;
	}

	let {
		surfaceId,
		component,
		weight,
		processor,
		theme,
		value,
		minValue,
		maxValue,
		label = ''
	}: Props = $props();

	const inputId = generateId('a2ui-slider');

	let currentValue = $derived(resolveNumber(processor, component, surfaceId, value) ?? 0);
	let min = $derived(resolveNumber(processor, component, surfaceId, minValue) ?? 0);
	let max = $derived(resolveNumber(processor, component, surfaceId, maxValue) ?? 100);

	let containerClasses = $derived(classMap(theme.components.Slider?.container));
	let inputClasses = $derived(classMap(theme.components.Slider?.element));
	let labelClasses = $derived(classMap(theme.components.Slider?.label));
	let containerStyles = $derived(styleMap(theme.additionalStyles?.Slider));

	function handleInput(event: Event) {
		const path = value?.path;

		if (!(event.target instanceof HTMLInputElement) || !path) {
			return;
		}

		processor.setData(component, path, parseFloat(event.target.value), surfaceId);
	}
</script>

<div class="a2ui-slider-host" style="--weight: {weight}">
	<section class={containerClasses} style={containerStyles}>
		<label for={inputId} class={labelClasses}>
			{label}
		</label>
		<input
			type="range"
			autocomplete="off"
			id={inputId}
			class={inputClasses}
			value={currentValue}
			min={min}
			max={max}
			oninput={handleInput}
		/>
		<span class={labelClasses}>{currentValue}</span>
	</section>
</div>

<style>
	.a2ui-slider-host {
		display: block;
		flex: var(--weight);
	}

	input {
		display: block;
		width: 100%;
	}
</style>

// renderers/lit/src/0.8/ui/slider.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { html, css, nothing } from "lit";
import { customElement, property } from "lit/decorators.js";
import { Root } from "./root.js";
import { A2uiMessageProcessor } from "@a2ui/web_core/data/model-processor";
import * as Primitives from "@a2ui/web_core/types/primitives";
import * as Types from "@a2ui/web_core/types/types";
import { classMap } from "lit/directives/class-map.js";
import { styleMap } from "lit/directives/style-map.js";
import { structuralStyles } from "./styles.js";
import { extractNumberValue, extractStringValue } from "./utils/utils.js";

@customElement("a2ui-slider")
export class Slider extends Root {
  @property()
  accessor value: Primitives.NumberValue | null = null;

  @property()
  accessor minValue = 0;

  @property()
  accessor maxValue = 0;

  @property()
  accessor label: Primitives.StringValue | null = null;

  static styles = [
    structuralStyles,
    css`
      * {
        box-sizing: border-box;
      }

      :host {
        display: block;
        flex: var(--weight);
      }

      input {
        display: block;
        width: 100%;
      }

      .description {
      }
    `,
  ];

  #setBoundValue(value: string) {
    if (!this.value || !this.processor) {
      return;
    }

    if (!("path" in this.value)) {
      return;
    }

    if (!this.value.path) {
      return;
    }

    this.processor.setData(
      this.component,
      this.value.path,
      value,
      this.surfaceId ?? A2uiMessageProcessor.DEFAULT_SURFACE_ID
    );
  }

  #renderField(value: string | number) {
    return html`<section
      class=${classMap(this.theme.components.Slider.container)}
    >
      ${this.label
        ? html`<label class=${classMap(this.theme.components.Slider.label)} for="${this.id}-input">
            ${extractStringValue(
              this.label,
              this.component,
              this.processor,
              this.surfaceId
            )}
          </label>`
        : nothing}
      <input
        autocomplete="off"
        class=${classMap(this.theme.components.Slider.element)}
        style=${this.theme.additionalStyles?.Slider
          ? styleMap(this.theme.additionalStyles?.Slider)
          : nothing}
        @input=${(evt: Event) => {
          if (!(evt.target instanceof HTMLInputElement)) {
            return;
          }

          this.#setBoundValue(evt.target.value);
        }}
        id="${this.id}-input"
        name=${this.id}
        .value=${value}
        type="range"
        min=${this.minValue ?? "0"}
        max=${this.maxValue ?? "0"}
      />
      <span class=${classMap(this.theme.components.Slider.label)}
        >${this.value
          ? extractNumberValue(
              this.value,
              this.component,
              this.processor,
              this.surfaceId
            )
          : "0"}</span
      >
    </section>`;
  }

  render() {
    if (this.value && typeof this.value === "object") {
      if ("literalNumber" in this.value && this.value.literalNumber) {
        return this.#renderField(this.value.literalNumber);
      } else if ("literal" in this.value && this.value.literal !== undefined) {
        return this.#renderField(this.value.literal);
      } else if (this.value && "path" in this.value && this.value.path) {
        if (!this.processor || !this.component) {
          return html`(no processor)`;
        }

        const textValue = this.processor.getData(
          this.component,
          this.value.path,
          this.surfaceId ?? A2uiMessageProcessor.DEFAULT_SURFACE_ID
        );

        if (textValue === null) {
          return html`Invalid value`;
        }

        if (typeof textValue !== "string" && typeof textValue !== "number") {
          return html`Invalid value`;
        }

        return this.#renderField(textValue);
      }
    }

    return nothing;
  }
}
