// renderers/svelte/src/Surface.svelte
<script lang="ts">
  import type { SurfaceGroupModel, ComponentApi } from '@a2ui/web_core/v0_9';
  import type { ComponentRegistry } from './core/types.js';
  import ComponentHost from './core/ComponentHost.svelte';

  interface Props {
    /** The surface group model containing all surfaces. */
    surfaceGroup: SurfaceGroupModel<ComponentApi>;
    /** The ID of the surface to render. */
    surfaceId: string;
    /** The component registry mapping type names to Svelte components. */
    registry: ComponentRegistry;
  }

  let { surfaceGroup, surfaceId, registry }: Props = $props();

  const surface = $derived(surfaceGroup.getSurface(surfaceId));
</script>

{#if surface}
  <div class="a2ui-surface" data-surface-id={surfaceId}>
    <ComponentHost
      {surface}
      componentId="root"
      dataContextPath="/"
      {registry}
    />
  </div>
{/if}

// renderers/react/src/v0_9/Surface.tsx
import React from 'react';
import { useA2UI } from './core/A2UIProvider.js';
import { ComponentHost } from './core/ComponentHost.js';

interface SurfaceProps {
  /** The ID of the surface to render. */
  surfaceId: string;
}

/**
 * Renders a single A2UI surface by ID.
 *
 * Must be used within an `<A2UIProvider>`.
 *
 * @example
 * ```tsx
 * <A2UIProvider catalog={catalog} registry={registry} onAction={handleAction}>
 *   <Surface surfaceId="main" />
 * </A2UIProvider>
 * ```
 */
export function Surface({ surfaceId }: SurfaceProps) {
  const { surfaceGroup, registry } = useA2UI();
  const surface = surfaceGroup.getSurface(surfaceId);

  if (!surface) return null;

  return (
    <div className="a2ui-surface" data-surface-id={surfaceId}>
      <ComponentHost
        surface={surface}
        componentId="root"
        dataContextPath="/"
        registry={registry}
      />
    </div>
  );
}
