// samples/client/react/projects/a2a-chat-canvas/src/components/Message.tsx
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { A2UIRenderer } from "@a2ui/react";
import { UiMessage, UiAgent, MessageDecoratorProps } from "../types";
import { formatTimestamp } from "../utils";
import { useChatContext } from "../context/ChatContext";

interface MessageProps {
  message: UiMessage;
  decorator?: React.ComponentType<MessageDecoratorProps>;
}

/**
 * Message component that displays a single chat message.
 */
export function Message({ message, decorator: Decorator }: MessageProps) {
  const { a2uiSurfaces } = useChatContext();
  const isUser = message.role.type === "ui_user";
  const isAgent = message.role.type === "ui_agent";
  const agentRole = isAgent ? (message.role as UiAgent) : null;

  const content = (
    <div className={`message ${isUser ? "user-message" : "agent-message"}`}>
      <div className="message-avatar">
        {isAgent && agentRole?.iconUrl ? (
          <img src={agentRole.iconUrl} alt={agentRole.name} />
        ) : isAgent ? (
          <div className="agent-avatar">{agentRole?.name?.charAt(0) || "A"}</div>
        ) : (
          <div className="user-avatar">U</div>
        )}
      </div>

      <div className="message-content">
        <div className="message-header">
          <span className="message-sender">
            {isAgent ? agentRole?.name : "You"}
            {agentRole?.subagentName && (
              <span className="subagent-name"> via {agentRole.subagentName}</span>
            )}
          </span>
          <span className="message-time">{formatTimestamp(message.created)}</span>
        </div>

        <div className="message-body">
          {message.status === "pending" && message.contents.length === 0 ? (
            <div className="loading-indicator">
              <span className="dot" />
              <span className="dot" />
              <span className="dot" />
            </div>
          ) : (
            message.contents.map((content) => (
              <MessageContent
                key={content.id}
                content={content}
                surfaceIds={Array.from(a2uiSurfaces.keys())}
              />
            ))
          )}
        </div>
      </div>
    </div>
  );

  if (Decorator) {
    return <Decorator message={message}>{content}</Decorator>;
  }

  return content;
}

interface MessageContentProps {
  content: UiMessage["contents"][0];
  surfaceIds: string[];
}

function MessageContent({ content, surfaceIds }: MessageContentProps) {
  if (content.data.kind === "text") {
    return <p className="text-content">{content.data.text}</p>;
  }

  if (content.variant === "a2ui_data_part") {
    return (
      <div className="a2ui-content">
        {surfaceIds.map((surfaceId) => (
          <A2UIRenderer
            key={surfaceId}
            surfaceId={surfaceId}
            className="embedded-surface"
          />
        ))}
      </div>
    );
  }

  return <pre className="json-content">{JSON.stringify(content.data, null, 2)}</pre>;
}

// samples/client/angular/projects/a2a_chat_canvas/src/lib/components/chat/message/message.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { A2aRenderer } from '@a2a-chat-canvas/a2a_renderer/a2a_renderer';
import { AgentHeader } from '@a2a-chat-canvas/components/chat/agent_header/agent-header';
import { ChatService } from '@a2a-chat-canvas/services/chat-service';
import { Role, UiAgent, UiMessage, UiMessageContent } from '@a2a-chat-canvas/types/ui-message';
import { isAgentThought } from '@a2a-chat-canvas/utils/a2a';
import { isA2aPart } from '@a2a-chat-canvas/utils/type-guards';
import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';

/** UI message component. */
@Component({
  selector: 'message',
  templateUrl: './message.html',
  styleUrl: './message.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [AgentHeader, A2aRenderer],
})
export class Message {
  /** The UI message to display. */
  readonly message = input.required<UiMessage>();

  /** Service for managing chat interactions. */
  private readonly chatService = inject(ChatService);

  protected getAgentName(role: UiAgent) {
    const rootagentName = role.name;
    return role.subagentName ? `${rootagentName} + ${role.subagentName}` : rootagentName;
  }

  /** Agent thought contents. */
  protected readonly agentThoughts = computed(() =>
    this.message().contents.filter((content) => containsAgentThought(content)),
  );
  /** Agent non-thought contents. */
  protected readonly messageContents = computed(() =>
    this.message().contents.filter((content) => !containsAgentThought(content)),
  );
  /** Whether the message is pending. */
  protected readonly showProgressIndicator = computed(() => {
    return this.message().status === 'pending';
  });
  /** A2UI surfaces in the conversation. */
  protected readonly surfaces = computed(() => this.chatService.a2uiSurfaces());

  /**
   * Type guard to check if the role is of type UiAgent.
   * @param role The role to check.
   * @returns True if the role is a UiAgent.
   */
  protected isRoleAgent(role: Role): role is UiAgent {
    return role.type === 'ui_agent';
  }
}

/**
 * Checks if the UI message content contains an agent thought.
 * @param content The UI message content to check.
 * @returns True if the content contains an agent thought.
 */
function containsAgentThought(content: UiMessageContent): boolean {
  if (isA2aPart(content.data)) {
    return isAgentThought(content.data);
  }
  return false;
}
