// renderers/lit/src/0.8/lit/standard_catalog_implementation/text.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { html, TemplateResult } from 'lit';
import { ComponentRenderer } from '../../core/types/types';
import { TextNode } from '../../core/types/types.js';
import '../components/text.js';

export const litTextRenderer: ComponentRenderer<TextNode, TemplateResult> = {
  componentName: 'Text',

  render(node, renderChild) {
    return html`
      <a2ui-text
        .node=${node}
        .renderChild=${renderChild}
      ></a2ui-text>
    `;
  },
};

// angular/projects/lib/src/lib/catalog/text.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import { Component, computed, input } from '@angular/core';
import { DynamicComponent } from '../rendering/dynamic-component';
import { v0_8 } from '@a2ui/web-lib';

@Component({
  selector: 'a2ui-text',
  template: `{{ resolvedText() }}`,
  host: {
    '[class]': 'theme.components.Text',
    '[style]': 'theme.additionalStyles?.Text',
  },
  styles: `
    :host {
      display: block;
      flex: var(--weight);
    }
  `,
})
export class Text extends DynamicComponent {
  readonly text = input.required<v0_8.Primitives.StringValue | null>();

  protected resolvedText = computed(() => {
    // TODO: Markdown?
    return super.resolvePrimitive(this.text()) ?? '(empty)';
  });
}
