// renderers/react/src/components/catalog/Row.tsx
import { Types } from '@a2ui/lit/0.8';
import { CatalogComponentProps } from './index';
import { ChildRenderer } from '../Renderer';

export function Row({ surfaceId, component }: CatalogComponentProps) {
  const node = component as Types.RowNode;
  const { alignment = 'stretch', distribution = 'start', children } = node.properties;

  const alignItems = alignment === 'stretch' ? 'stretch' :
    alignment === 'start' ? 'flex-start' :
    alignment === 'end' ? 'flex-end' : 'center';

  const justifyContent = distribution === 'start' ? 'flex-start' :
    distribution === 'end' ? 'flex-end' :
    distribution === 'center' ? 'center' :
    distribution === 'spaceAround' ? 'space-around' :
    distribution === 'spaceBetween' ? 'space-between' :
    distribution === 'spaceEvenly' ? 'space-evenly' : 'flex-start';

  const style: React.CSSProperties = {
    display: 'flex',
    flexDirection: 'row',
    alignItems,
    justifyContent,
    gap: '16px',
    flex: component.weight ?? 'initial',
  };

  return (
    <div data-id={component.id} style={style}>
      <ChildRenderer surfaceId={surfaceId} children={children} />
    </div>
  );
}

// samples/client/nativescript/src/app/components/row.component.ts
import { Component, ChangeDetectionStrategy, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptCommonModule } from '@nativescript/angular';
import { DynamicComponent, Renderer } from '@a2ui/nativescript';
import { Types, SimpleNode } from '../../a2ui-lit-types';

@Component({
  selector: 'a2ui-row',
  imports: [NativeScriptCommonModule, Renderer],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <FlexboxLayout 
      class="a2ui-row"
      flexDirection="row"
      [alignItems]="alignItems"
      [justifyContent]="justifyContent">
      <ng-container *ngFor="let child of children">
        <ng-container 
          a2ui-renderer
          [surfaceId]="surfaceId()"
          [component]="child">
        </ng-container>
      </ng-container>
    </FlexboxLayout>
  `,
  styles: [`
    .a2ui-row {
      flex-wrap: wrap;
    }
  `],
  schemas: [NO_ERRORS_SCHEMA],
})
export class RowComponent extends DynamicComponent<any> {
  get children(): SimpleNode[] {
    const node = this.node as SimpleNode;
    return node?.children || [];
  }
  
  get alignItems(): string {
    const node = this.node as SimpleNode;
    switch (node?.verticalAlignment) {
      case 'top': return 'flex-start';
      case 'bottom': return 'flex-end';
      case 'center': return 'center';
      default: return 'flex-start';
    }
  }
  
  get justifyContent(): string {
    const node = this.node as SimpleNode;
    switch (node?.horizontalAlignment) {
      case 'start': return 'flex-start';
      case 'end': return 'flex-end';
      case 'center': return 'center';
      case 'spaceBetween': return 'space-between';
      case 'spaceAround': return 'space-around';
      default: return 'flex-start';
    }
  }
}
