// renderers/angular/src/v0_8/data/markdown.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Injectable } from '@angular/core';
import { Types } from '../types';

@Injectable({
  providedIn: 'root',
})
export abstract class MarkdownRenderer {
  abstract render(markdown: string, options?: Types.MarkdownRendererOptions): Promise<string>;
}

@Injectable({
  providedIn: 'root',
})
export class DefaultMarkdownRenderer extends MarkdownRenderer {
  override async render(markdown: string, options?: Types.MarkdownRendererOptions): Promise<string> {
    // Basic implementation for v0.8
    return markdown;
  }
}

export function provideMarkdownRenderer() {
  return { provide: MarkdownRenderer, useClass: DefaultMarkdownRenderer };
}

// renderers/lit/src/0.8/ui/context/markdown.ts
/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */
import {
  DirectiveResult,
} from "lit/directive.js";
import { createContext } from "@lit/context";

/**
 * A Lit Context to override the default (noop) markdown renderer.
 */
export const markdownContext = createContext<DirectiveResult>(
  Symbol("a2ui-lit-markdown-renderer")
);
