// renderers/vue2/src/lib/catalog/image.vue
<!--
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<template>
  <div
    class="a2ui-image"
    :class="classes"
    :style="[weightStyle, theme.additionalStyles && theme.additionalStyles.Image]"
  >
    <img
      v-if="resolvedUrl"
      :src="resolvedUrl"
      :style="imageStyle"
      alt=""
    />
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import type { PropType } from 'vue';
import type { Primitives, Types } from '@a2ui/lit/0.8';
import { Styles } from '@a2ui/lit/0.8';
import DynamicComponentMixin from '../rendering/mixins/dynamic-component';

export default Vue.extend({
  name: 'A2UIImage',

  mixins: [DynamicComponentMixin],

  props: {
    url: {
      type: Object as PropType<Primitives.StringValue | null>,
      required: true,
    },
    usageHint: {
      type: String as PropType<Types.ResolvedImage['usageHint'] | null>,
      default: null,
    },
    fit: {
      type: String as PropType<Types.ResolvedImage['fit'] | null>,
      default: null,
    },
  },

  computed: {
    resolvedUrl(): string | null {
      return (this as any).resolvePrimitive(this.url);
    },

    classes(): Record<string, boolean> {
      const usageHint = this.usageHint;
      const theme = (this as any).theme as Types.Theme;

      return Styles.merge(
        theme.components.Image.all,
        usageHint ? theme.components.Image[usageHint as keyof typeof theme.components.Image] : {}
      );
    },

    imageStyle(): Record<string, string> {
      const fit = this.fit || 'contain';
      return {
        objectFit: fit,
        width: '100%',
        height: '100%',
      };
    },
  },
});
</script>

<style>
.a2ui-image {
  display: block;
  flex: var(--weight);
  overflow: hidden;
}

.a2ui-image img {
  display: block;
}
</style>

// renderers/angular/src/v0_8/components/image.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import * as Primitives from '@a2ui/web_core/types/primitives';
import * as Styles from '@a2ui/web_core/styles/index';
import { Types } from '../types';
import { DynamicComponent } from '../rendering/dynamic-component';

@Component({
  selector: 'a2ui-image',
  changeDetection: ChangeDetectionStrategy.Eager,
  styles: `
    :host {
      display: block;
      flex: var(--weight);
      min-height: 0;
      overflow: auto;
    }

    img {
      display: block;
      width: 100%;
      height: 100%;
      box-sizing: border-box;
    }
  `,
  template: `
    @let resolvedUrl = this.resolvedUrl();
    @let resolvedAltText = this.resolvedAltText();

    @if (resolvedUrl) {
      <section [class]="classes()" [style]="theme.additionalStyles?.Image">
        <img [src]="resolvedUrl" [alt]="resolvedAltText" />
      </section>
    }
  `,
})
export class Image extends DynamicComponent<Types.ImageNode> {
  readonly url = input.required<Primitives.StringValue | null>();
  readonly usageHint = input.required<Types.ResolvedImage['usageHint'] | null>();
  readonly altText = input.required<Primitives.StringValue | null>();

  protected readonly resolvedUrl = computed(() => this.resolvePrimitive(this.url()));
  protected readonly resolvedAltText = computed(() => {
    const raw = this.altText();
    return raw ? this.resolvePrimitive(raw) : '';
  });

  protected classes = computed(() => {
    const usageHint = this.usageHint();
    const imageTheme = this.theme.components.Image;

    return Styles.merge(
      imageTheme.all,
      usageHint && usageHint in imageTheme ? imageTheme[usageHint as keyof typeof imageTheme] : {},
    );
  });
}
